@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.annotation.DrawableRes
import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons
import io.channel.bezier.compose.R

val BezierIcons.AppCheck: BezierIcon
    get() = object : BezierIcon {
        @DrawableRes
        override val resourceId: Int = R.drawable.icon_app_check
        override val imageVector: ImageVector
            get() = _appCheck ?: ImageVector.Builder(
                    name = "AppCheck",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                ) {
                    moveTo(12.0f, 5.0f)
                    lineTo(10.4f, 5.0f)
                    curveTo(9.264000000000001f, 5.0f, 8.471f, 5.0f, 7.854000000000001f, 5.05f)
                    curveTo(7.2490000000000006f, 5.1f, 6.901000000000001f, 5.193f, 6.638000000000001f, 5.327f)
                    arcTo(3.0f, 3.0f, 242.98511827035634f, isMoreThanHalf = false, isPositiveArc = false, 5.328000000000001f, 6.6370000000000005f)
                    curveTo(5.193000000000001f, 6.901000000000001f, 5.100000000000001f, 7.2490000000000006f, 5.051000000000001f, 7.854000000000001f)
                    curveTo(5.0f, 8.471f, 5.0f, 9.264f, 5.0f, 10.4f)
                    lineTo(5.0f, 13.600000000000001f)
                    curveTo(5.0f, 14.736f, 5.0f, 15.529000000000002f, 5.05f, 16.145000000000003f)
                    curveTo(5.1f, 16.751000000000005f, 5.193f, 17.099000000000004f, 5.327f, 17.362000000000002f)
                    arcTo(3.0f, 3.0f, 152.9851182703563f, isMoreThanHalf = false, isPositiveArc = false, 6.6370000000000005f, 18.672f)
                    curveTo(6.901000000000001f, 18.807000000000002f, 7.2490000000000006f, 18.900000000000002f, 7.854000000000001f, 18.949f)
                    curveTo(8.471f, 18.999000000000002f, 9.264000000000001f, 19.0f, 10.4f, 19.0f)
                    lineTo(13.600000000000001f, 19.0f)
                    curveTo(14.736f, 19.0f, 15.529000000000002f, 19.0f, 16.145000000000003f, 18.95f)
                    curveTo(16.751000000000005f, 18.9f, 17.099000000000004f, 18.807f, 17.362000000000002f, 18.673f)
                    arcTo(3.0f, 3.0f, 62.98511827035632f, isMoreThanHalf = false, isPositiveArc = false, 18.672f, 17.363f)
                    curveTo(18.807000000000002f, 17.099f, 18.900000000000002f, 16.751f, 18.949f, 16.145f)
                    curveTo(19.0f, 15.53f, 19.0f, 14.736f, 19.0f, 13.6f)
                    lineTo(19.0f, 13.0f)
                    lineTo(21.0f, 13.0f)
                    lineTo(21.0f, 13.643f)
                    curveTo(21.0f, 14.726f, 21.0f, 15.601f, 20.942f, 16.309f)
                    curveTo(20.882f, 17.037000000000003f, 20.757f, 17.677f, 20.455000000000002f, 18.269000000000002f)
                    arcTo(5.0f, 5.0f, 26.98331402366245f, isMoreThanHalf = false, isPositiveArc = true, 18.270000000000003f, 20.455000000000002f)
                    curveTo(17.677000000000003f, 20.757f, 17.037000000000003f, 20.883000000000003f, 16.309000000000005f, 20.942f)
                    curveTo(15.6f, 21.0f, 14.726f, 21.0f, 13.643f, 21.0f)
                    lineTo(10.357000000000001f, 21.0f)
                    curveTo(9.274000000000001f, 21.0f, 8.399000000000001f, 21.0f, 7.691000000000001f, 20.942f)
                    curveTo(6.963000000000001f, 20.882f, 6.323f, 20.757f, 5.731000000000001f, 20.455000000000002f)
                    arcTo(5.0f, 5.0f, 116.98331402366246f, isMoreThanHalf = false, isPositiveArc = true, 3.545000000000001f, 18.270000000000003f)
                    curveTo(3.2430000000000008f, 17.677000000000003f, 3.117000000000001f, 17.037000000000003f, 3.0580000000000007f, 16.309000000000005f)
                    curveTo(3.0f, 15.6f, 3.0f, 14.726f, 3.0f, 13.643f)
                    lineTo(3.0f, 10.357000000000001f)
                    curveTo(3.0f, 9.274000000000001f, 3.0f, 8.399000000000001f, 3.058f, 7.691000000000001f)
                    curveTo(3.118f, 6.963000000000001f, 3.243f, 6.323f, 3.545f, 5.731000000000001f)
                    arcTo(5.0f, 5.0f, 206.96595034079928f, isMoreThanHalf = false, isPositiveArc = true, 5.73f, 3.544f)
                    curveTo(6.323f, 3.242f, 6.963000000000001f, 3.116f, 7.691000000000001f, 3.057f)
                    curveTo(8.4f, 3.0f, 9.274f, 3.0f, 10.357f, 3.0f)
                    lineTo(12.0f, 3.0f)
                    close()
                    moveTo(19.469f, 5.293f)
                    arcTo(1.0f, 1.0f, 224.00425538642233f, isMoreThanHalf = true, isPositiveArc = true, 20.883000000000003f, 6.707f)
                    lineTo(15.063000000000002f, 12.527000000000001f)
                    arcTo(0.44f, 0.44f, 45.390369173390305f, isMoreThanHalf = false, isPositiveArc = true, 14.445000000000002f, 12.527000000000001f)
                    lineTo(11.293000000000003f, 9.374f)
                    arcTo(1.0f, 1.0f, 135.99574461357975f, isMoreThanHalf = false, isPositiveArc = true, 12.707000000000003f, 7.960000000000001f)
                    lineTo(14.755000000000003f, 10.007000000000001f)
                    close()
                }
            }.build().also {
                _appCheck = it
            }
    }


private var _appCheck: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun AppCheckIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.AppCheck.imageVector,
            contentDescription = null,
    )
}
