@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.ArrowTurnLeftDown: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _arrowTurnLeftDown ?: ImageVector.Builder(
                    name = "ArrowTurnLeftDown",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                ) {
                    moveTo(7.79289f, 9.79289f)
                    curveTo(8.18342f, 9.40237f, 8.81658f, 9.40237f, 9.20711f, 9.79289f)
                    curveTo(9.59763f, 10.1834f, 9.59763f, 10.8166f, 9.20711f, 11.2071f)
                    lineTo(6.41421f, 14.0f)
                    lineTo(15.0f, 14.0f)
                    curveTo(17.7614f, 14.0f, 20.0f, 11.7614f, 20.0f, 9.0f)
                    lineTo(20.0f, 5.0f)
                    curveTo(20.0f, 4.44772f, 20.4477f, 4.0f, 21.0f, 4.0f)
                    curveTo(21.5523f, 4.0f, 22.0f, 4.44772f, 22.0f, 5.0f)
                    lineTo(22.0f, 9.0f)
                    curveTo(22.0f, 12.866f, 18.866f, 16.0f, 15.0f, 16.0f)
                    lineTo(6.41421f, 16.0f)
                    lineTo(9.20711f, 18.7929f)
                    curveTo(9.59763f, 19.1834f, 9.59763f, 19.8166f, 9.20711f, 20.2071f)
                    curveTo(8.81658f, 20.5976f, 8.18342f, 20.5976f, 7.79289f, 20.2071f)
                    lineTo(3.29289f, 15.7071f)
                    curveTo(2.90237f, 15.3166f, 2.90237f, 14.6834f, 3.29289f, 14.2929f)
                    lineTo(7.79289f, 9.79289f)
                    close()
                }
            }.build().also {
                _arrowTurnLeftDown = it
            }
    }


private var _arrowTurnLeftDown: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun ArrowTurnLeftDownIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.ArrowTurnLeftDown.imageVector,
            contentDescription = null,
    )
}
