@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.Asterisk: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _asterisk ?: ImageVector.Builder(
                    name = "Asterisk",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                ) {
                    moveTo(12.0f, 2.5f)
                    arcTo(1.0f, 1.0f, 270.0f, isMoreThanHalf = false, isPositiveArc = true, 13.0f, 3.5f)
                    lineTo(13.0f, 10.268f)
                    lineTo(18.861f, 6.884f)
                    arcTo(1.0f, 1.0f, 239.61921222659703f, isMoreThanHalf = true, isPositiveArc = true, 19.861f, 8.616f)
                    lineTo(14.0f, 12.0f)
                    lineTo(19.861f, 15.384f)
                    arcTo(1.0f, 1.0f, 299.6206677882518f, isMoreThanHalf = true, isPositiveArc = true, 18.861f, 17.116f)
                    lineTo(13.0f, 13.732f)
                    lineTo(13.0f, 20.5f)
                    arcTo(1.0f, 1.0f, 0.0f, isMoreThanHalf = true, isPositiveArc = true, 11.0f, 20.5f)
                    lineTo(11.0f, 13.732f)
                    lineTo(5.139f, 17.116f)
                    arcTo(1.0f, 1.0f, 59.61921222659702f, isMoreThanHalf = true, isPositiveArc = true, 4.139f, 15.384f)
                    lineTo(10.0f, 12.0f)
                    lineTo(4.139f, 8.616f)
                    arcTo(1.0f, 1.0f, 120.3807877733996f, isMoreThanHalf = false, isPositiveArc = true, 5.139f, 6.8839999999999995f)
                    lineTo(11.0f, 10.268f)
                    lineTo(11.0f, 3.5f)
                    arcTo(1.0f, 1.0f, 180.0f, isMoreThanHalf = false, isPositiveArc = true, 12.0f, 2.5f)
                }
            }.build().also {
                _asterisk = it
            }
    }


private var _asterisk: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun AsteriskIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.Asterisk.imageVector,
            contentDescription = null,
    )
}
