@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon

val BezierIcon.Block: ImageVector
    get() {
        return io.channel.bezier.icon._block ?: ImageVector.Builder(
                name = "Block",
                defaultWidth = 24.dp,
                defaultHeight = 24.dp,
                viewportWidth = 24f,
                viewportHeight = 24f,
        ).apply {
            path(
                    fill = SolidColor(Color(0xFF313234)),
                    strokeLineWidth = 1f,
                    pathFillType = PathFillType.EvenOdd,
            ) {
                moveTo(22.0f, 12.0f)
                curveTo(22.0f, 6.4772f, 17.5228f, 2.0f, 12.0f, 2.0f)
                curveTo(6.4772f, 2.0f, 2.0f, 6.4772f, 2.0f, 12.0f)
                curveTo(2.0f, 17.5228f, 6.4772f, 22.0f, 12.0f, 22.0f)
                curveTo(17.5228f, 22.0f, 22.0f, 17.5228f, 22.0f, 12.0f)
                close()
                moveTo(20.0392f, 12.0f)
                curveTo(20.0392f, 16.4399f, 16.4399f, 20.0392f, 12.0f, 20.0392f)
                curveTo(10.1334f, 20.0392f, 8.4154f, 19.4031f, 7.051f, 18.3358f)
                lineTo(18.3358f, 7.051f)
                curveTo(19.4031f, 8.4154f, 20.0392f, 10.1334f, 20.0392f, 12.0f)
                close()
                moveTo(5.6645f, 16.9493f)
                lineTo(16.9493f, 5.6645f)
                curveTo(15.5848f, 4.597f, 13.8667f, 3.9608f, 12.0f, 3.9608f)
                curveTo(7.5601f, 3.9608f, 3.9608f, 7.5601f, 3.9608f, 12.0f)
                curveTo(3.9608f, 13.8667f, 4.597f, 15.5848f, 5.6645f, 16.9493f)
                close()
            }
        }.build().also {
            io.channel.bezier.icon._block = it
        }
    }

private var _block: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun BlockIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcon.Block,
            contentDescription = null,
    )
}
