@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.BookmarkFilled: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _bookmarkFilled ?: ImageVector.Builder(
                    name = "BookmarkFilled",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                ) {
                    moveTo(19.0072f, 4.99286f)
                    curveTo(19.0032f, 3.89113f, 18.109f, 3.00012f, 17.0073f, 3.00012f)
                    lineTo(6.9996f, 3.00012f)
                    curveTo(5.89503f, 3.00012f, 4.9996f, 3.89555f, 4.9996f, 5.00012f)
                    lineTo(4.9996f, 20.5774f)
                    curveTo(4.9996f, 21.4257f, 5.98939f, 21.8887f, 6.64054f, 21.345f)
                    lineTo(12.0356f, 16.8401f)
                    lineTo(17.4229f, 21.3384f)
                    curveTo(18.0753f, 21.8832f, 19.0669f, 21.4172f, 19.0638f, 20.5672f)
                    lineTo(19.0072f, 4.99286f)
                    close()
                }
            }.build().also {
                _bookmarkFilled = it
            }
    }


private var _bookmarkFilled: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun BookmarkFilledIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.BookmarkFilled.imageVector,
            contentDescription = null,
    )
}
