@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.Call: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _call ?: ImageVector.Builder(
                    name = "Call",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                ) {
                    moveTo(6.55271f, 4.53075f)
                    curveTo(6.17285f, 4.60505f, 5.75466f, 4.81443f, 5.40708f, 5.16202f)
                    curveTo(4.92656f, 5.64253f, 4.50976f, 6.77497f, 4.90901f, 8.55345f)
                    curveTo(5.30144f, 10.3015f, 6.47328f, 12.5614f, 8.95798f, 15.0461f)
                    curveTo(11.4427f, 17.5308f, 13.7026f, 18.7027f, 15.4507f, 19.0951f)
                    curveTo(17.2292f, 19.4944f, 18.3616f, 19.0776f, 18.8421f, 18.597f)
                    curveTo(19.1897f, 18.2495f, 19.3991f, 17.8313f, 19.4734f, 17.4514f)
                    curveTo(19.5492f, 17.0636f, 19.4744f, 16.7919f, 19.3733f, 16.6462f)
                    lineTo(19.368f, 16.6385f)
                    lineTo(19.3628f, 16.6307f)
                    curveTo(19.1946f, 16.3786f, 18.8075f, 15.9831f, 18.3057f, 15.6512f)
                    curveTo(17.7952f, 15.3136f, 17.3132f, 15.1392f, 16.9667f, 15.1392f)
                    curveTo(16.7193f, 15.1392f, 16.4029f, 15.3057f, 15.907f, 15.7191f)
                    curveTo(15.8495f, 15.767f, 15.7832f, 15.8238f, 15.7124f, 15.8845f)
                    curveTo(15.5475f, 16.0258f, 15.3583f, 16.1879f, 15.2001f, 16.3065f)
                    curveTo(15.0057f, 16.4522f, 14.5769f, 16.7636f, 14.0416f, 16.753f)
                    curveTo(13.487f, 16.7421f, 12.7489f, 16.4751f, 12.0433f, 16.1025f)
                    curveTo(11.2959f, 15.7078f, 10.4488f, 15.1227f, 9.66509f, 14.339f)
                    curveTo(8.88142f, 13.5554f, 8.29631f, 12.7082f, 7.90161f, 11.9608f)
                    curveTo(7.52904f, 11.2552f, 7.26205f, 10.5171f, 7.25107f, 9.96247f)
                    curveTo(7.24047f, 9.42718f, 7.55192f, 8.99844f, 7.69761f, 8.80406f)
                    curveTo(7.81625f, 8.64578f, 7.97829f, 8.45667f, 8.11964f, 8.29172f)
                    curveTo(8.18028f, 8.22095f, 8.23711f, 8.15462f, 8.28507f, 8.09708f)
                    curveTo(8.69841f, 7.60122f, 8.86493f, 7.28484f, 8.86493f, 7.03739f)
                    curveTo(8.86493f, 6.69094f, 8.69056f, 6.20894f, 8.35294f, 5.69844f)
                    curveTo(8.02105f, 5.19662f, 7.62556f, 4.80947f, 7.37336f, 4.64133f)
                    lineTo(7.3656f, 4.63616f)
                    lineTo(7.35794f, 4.63084f)
                    curveTo(7.21219f, 4.5297f, 6.94056f, 4.45488f, 6.55271f, 4.53075f)
                    close()
                    moveTo(8.49031f, 2.98228f)
                    curveTo(7.79366f, 2.50264f, 6.939f, 2.41728f, 6.16877f, 2.56794f)
                    curveTo(5.38765f, 2.72074f, 4.61371f, 3.12696f, 3.99286f, 3.7478f)
                    curveTo(2.85933f, 4.88133f, 2.4691f, 6.81559f, 2.95758f, 8.99153f)
                    curveTo(3.45288f, 11.1979f, 4.86351f, 13.7801f, 7.54377f, 16.4604f)
                    curveTo(10.224f, 19.1406f, 12.8063f, 20.5512f, 15.0126f, 21.0465f)
                    curveTo(17.1885f, 21.535f, 19.1228f, 21.1448f, 20.2563f, 20.0113f)
                    curveTo(20.8772f, 19.3904f, 21.2834f, 18.6165f, 21.4362f, 17.8353f)
                    curveTo(21.5868f, 17.0651f, 21.5015f, 16.2105f, 21.0219f, 15.5139f)
                    curveTo(20.6728f, 14.9934f, 20.0754f, 14.4238f, 19.4089f, 13.983f)
                    curveTo(18.748f, 13.5459f, 17.8742f, 13.1392f, 16.9667f, 13.1392f)
                    curveTo(15.923f, 13.1392f, 15.1025f, 13.786f, 14.6265f, 14.1828f)
                    curveTo(14.5124f, 14.2778f, 14.4192f, 14.358f, 14.3376f, 14.4282f)
                    curveTo(14.2085f, 14.5392f, 14.1084f, 14.6253f, 14.0005f, 14.7061f)
                    curveTo(13.9871f, 14.7162f, 13.9748f, 14.7252f, 13.9637f, 14.7331f)
                    curveTo(13.9029f, 14.7192f, 13.8267f, 14.698f, 13.7357f, 14.6674f)
                    curveTo(13.5289f, 14.598f, 13.2698f, 14.4884f, 12.9772f, 14.3339f)
                    curveTo(12.3915f, 14.0247f, 11.7098f, 13.5554f, 11.0793f, 12.9248f)
                    curveTo(10.4488f, 12.2943f, 9.97946f, 11.6126f, 9.67018f, 11.0269f)
                    curveTo(9.51571f, 10.7344f, 9.40617f, 10.4752f, 9.33672f, 10.2684f)
                    curveTo(9.30617f, 10.1774f, 9.28494f, 10.1012f, 9.27102f, 10.0405f)
                    curveTo(9.27895f, 10.0293f, 9.2879f, 10.017f, 9.29798f, 10.0036f)
                    curveTo(9.37878f, 9.89577f, 9.46491f, 9.79562f, 9.57589f, 9.66657f)
                    curveTo(9.64611f, 9.58492f, 9.72628f, 9.4917f, 9.82134f, 9.37766f)
                    curveTo(10.2182f, 8.90161f, 10.8649f, 8.08117f, 10.8649f, 7.03739f)
                    curveTo(10.8649f, 6.12992f, 10.4582f, 5.25612f, 10.0211f, 4.59518f)
                    curveTo(9.58038f, 3.92877f, 9.01082f, 3.33137f, 8.49031f, 2.98228f)
                    close()
                    moveTo(9.21524f, 10.1283f)
                    curveTo(9.21519f, 10.1283f, 9.21575f, 10.127f, 9.21711f, 10.1244f)
                    curveTo(9.21598f, 10.127f, 9.2153f, 10.1283f, 9.21524f, 10.1283f)
                    close()
                    moveTo(13.8758f, 14.7889f)
                    curveTo(13.8758f, 14.7888f, 13.8772f, 14.7881f, 13.8797f, 14.787f)
                    curveTo(13.8771f, 14.7884f, 13.8758f, 14.7889f, 13.8758f, 14.7889f)
                    close()
                }
            }.build().also {
                _call = it
            }
    }


private var _call: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun CallIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.Call.imageVector,
            contentDescription = null,
    )
}
