@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.annotation.DrawableRes
import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons
import io.channel.bezier.compose.R

val BezierIcons.CenterFocus: BezierIcon
    get() = object : BezierIcon {
        @DrawableRes
        override val resourceId: Int = R.drawable.icon_center_focus
        override val imageVector: ImageVector
            get() = _centerFocus ?: ImageVector.Builder(
                    name = "CenterFocus",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        pathFillType = PathFillType.EvenOdd,
                ) {
                    moveTo(21.0f, 10.0f)
                    lineTo(19.0f, 10.0f)
                    lineTo(19.0f, 5.0f)
                    lineTo(14.0f, 5.0f)
                    lineTo(14.0f, 3.0f)
                    lineTo(19.5f, 3.0f)
                    curveTo(20.326999999999998f, 3.0f, 21.0f, 3.673f, 21.0f, 4.5f)
                    close()
                    moveTo(19.5f, 21.0f)
                    lineTo(14.0f, 21.0f)
                    lineTo(14.0f, 19.0f)
                    lineTo(19.0f, 19.0f)
                    lineTo(19.0f, 14.0f)
                    lineTo(21.0f, 14.0f)
                    lineTo(21.0f, 19.5f)
                    curveTo(21.0f, 20.326999999999998f, 20.326999999999998f, 21.0f, 19.5f, 21.0f)
                    moveTo(4.5f, 21.0f)
                    lineTo(10.0f, 21.0f)
                    lineTo(10.0f, 19.0f)
                    lineTo(5.0f, 19.0f)
                    lineTo(5.0f, 14.0f)
                    lineTo(3.0f, 14.0f)
                    lineTo(3.0f, 19.5f)
                    curveTo(3.0f, 20.326999999999998f, 3.673f, 21.0f, 4.5f, 21.0f)
                    moveTo(5.0f, 10.0f)
                    lineTo(3.0f, 10.0f)
                    lineTo(3.0f, 4.5f)
                    curveTo(3.0f, 3.673f, 3.673f, 3.0f, 4.5f, 3.0f)
                    lineTo(10.0f, 3.0f)
                    lineTo(10.0f, 5.0f)
                    lineTo(5.0f, 5.0f)
                    close()
                    moveTo(12.0f, 16.0f)
                    arcTo(4.0f, 4.0f, 90.0f, isMoreThanHalf = true, isPositiveArc = false, 12.0f, 8.0f)
                    arcTo(4.0f, 4.0f, 270.0f, isMoreThanHalf = false, isPositiveArc = false, 12.0f, 16.0f)
                }
            }.build().also {
                _centerFocus = it
            }
    }


private var _centerFocus: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun CenterFocusIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.CenterFocus.imageVector,
            contentDescription = null,
    )
}
