@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.annotation.DrawableRes
import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons
import io.channel.bezier.compose.R

val BezierIcons.CodeBlock: BezierIcon
    get() = object : BezierIcon {
        @DrawableRes
        override val resourceId: Int = R.drawable.icon_code_block
        override val imageVector: ImageVector
            get() = _codeBlock ?: ImageVector.Builder(
                    name = "CodeBlock",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF000000)),
                        strokeLineWidth = 1f,
                ) {
                    moveTo(8.0f, 5.054f)
                    lineTo(7.879f, 5.062f)
                    curveTo(7.169f, 5.12f, 6.843999999999999f, 5.222f, 6.638f, 5.328f)
                    arcTo(3.0f, 3.0f, 242.98511827035634f, isMoreThanHalf = false, isPositiveArc = false, 5.327999999999999f, 6.638f)
                    curveTo(5.2219999999999995f, 6.844f, 5.119999999999999f, 7.17f, 5.061999999999999f, 7.879f)
                    curveTo(5.002f, 8.613f, 5.0f, 9.568f, 5.0f, 11.001f)
                    lineTo(5.0f, 13.001f)
                    curveTo(5.0f, 14.433f, 5.002f, 15.388f, 5.062f, 16.121f)
                    curveTo(5.12f, 16.831f, 5.222f, 17.157f, 5.327f, 17.363f)
                    arcTo(3.0f, 3.0f, 152.9851182703563f, isMoreThanHalf = false, isPositiveArc = false, 6.6370000000000005f, 18.673f)
                    curveTo(6.844f, 18.778f, 7.1690000000000005f, 18.880999999999997f, 7.8790000000000004f, 18.939f)
                    curveTo(8.612f, 18.999f, 9.567f, 19.0f, 11.0f, 19.0f)
                    lineTo(13.0f, 19.0f)
                    curveTo(14.433f, 19.0f, 15.388f, 18.999f, 16.121f, 18.939f)
                    curveTo(16.831f, 18.881f, 17.157f, 18.779f, 17.362f, 18.673000000000002f)
                    arcTo(3.0f, 3.0f, 62.98511827035632f, isMoreThanHalf = false, isPositiveArc = false, 18.671999999999997f, 17.363000000000003f)
                    curveTo(18.778f, 17.157000000000004f, 18.880999999999997f, 16.831000000000003f, 18.938999999999997f, 16.122000000000003f)
                    curveTo(18.964999999999996f, 15.798000000000004f, 18.978999999999996f, 15.432000000000004f, 18.986999999999995f, 15.001000000000003f)
                    lineTo(20.986999999999995f, 15.001000000000003f)
                    curveTo(20.956999999999994f, 16.539f, 20.850999999999996f, 17.492000000000004f, 20.454999999999995f, 18.270000000000003f)
                    arcTo(5.0f, 5.0f, 26.98331402366245f, isMoreThanHalf = false, isPositiveArc = true, 18.269999999999996f, 20.456000000000003f)
                    curveTo(17.2f, 21.0f, 15.8f, 21.0f, 13.0f, 21.0f)
                    lineTo(11.0f, 21.0f)
                    curveTo(8.2f, 21.0f, 6.8f, 21.0f, 5.73f, 20.456f)
                    arcTo(5.0f, 5.0f, 117.00953034876586f, isMoreThanHalf = false, isPositiveArc = true, 3.5450000000000004f, 18.27f)
                    curveTo(3.0f, 17.2f, 3.0f, 15.8f, 3.0f, 13.0f)
                    lineTo(3.0f, 11.0f)
                    curveTo(3.0f, 8.2f, 3.0f, 6.8f, 3.545f, 5.73f)
                    arcTo(5.0f, 5.0f, 207.00068262716798f, isMoreThanHalf = false, isPositiveArc = true, 5.73f, 3.545f)
                    curveTo(6.324000000000001f, 3.243f, 7.0200000000000005f, 3.1109999999999998f, 8.0f, 3.051f)
                    close()
                    moveTo(16.586f, 3.094f)
                    arcTo(1.0f, 1.0f, 203.03762129471255f, isMoreThanHalf = true, isPositiveArc = true, 18.412999999999997f, 3.907f)
                    lineTo(14.412999999999997f, 12.907f)
                    arcTo(1.0f, 1.0f, 24.93972141501172f, isMoreThanHalf = false, isPositiveArc = true, 12.585999999999997f, 12.094f)
                    close()
                    moveTo(18.292f, 7.294f)
                    curveTo(18.682000000000002f, 6.903f, 19.316000000000003f, 6.903f, 19.707f, 7.294f)
                    lineTo(21.707f, 9.294f)
                    arcTo(1.0f, 1.0f, 315.0491454789827f, isMoreThanHalf = false, isPositiveArc = true, 21.707f, 10.707f)
                    lineTo(19.707f, 12.707f)
                    arcTo(1.001f, 1.001f, 47.26685313960511f, isMoreThanHalf = false, isPositiveArc = true, 18.292f, 11.293000000000001f)
                    lineTo(19.585f, 10.001000000000001f)
                    lineTo(18.292f, 8.708000000000002f)
                    arcTo(1.0f, 1.0f, 134.96812921607167f, isMoreThanHalf = false, isPositiveArc = true, 18.292f, 7.293000000000002f)
                    moveTo(11.292000000000002f, 3.293000000000002f)
                    arcTo(1.001f, 1.001f, 227.2668531396051f, isMoreThanHalf = false, isPositiveArc = true, 12.707f, 4.707000000000002f)
                    lineTo(11.414f, 6.0f)
                    lineTo(12.706999999999999f, 7.293f)
                    arcTo(1.0f, 1.0f, 315.0f, isMoreThanHalf = false, isPositiveArc = true, 11.291999999999998f, 8.708f)
                    lineTo(9.291999999999998f, 6.708f)
                    arcTo(1.0f, 1.0f, 134.96812921607167f, isMoreThanHalf = false, isPositiveArc = true, 9.291999999999998f, 5.293f)
                    close()
                }
            }.build().also {
                _codeBlock = it
            }
    }


private var _codeBlock: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun CodeBlockIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.CodeBlock.imageVector,
            contentDescription = null,
    )
}
