@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon

val BezierIcon.CodeBlock: ImageVector
    get() {
        return _codeBlock ?: ImageVector.Builder(
                name = "CodeBlock",
                defaultWidth = 24.dp,
                defaultHeight = 24.dp,
                viewportWidth = 24f,
                viewportHeight = 24f,
        ).apply {
            path(
                    fill = SolidColor(Color(0xFF313234)),
                    strokeLineWidth = 1f,
                    pathFillType = PathFillType.EvenOdd,
            ) {
                moveTo(18.4138f, 3.9061f)
                curveTo(18.6381f, 3.4015f, 18.4108f, 2.8105f, 17.9061f, 2.5862f)
                curveTo(17.4015f, 2.3619f, 16.8105f, 2.5892f, 16.5862f, 3.0939f)
                lineTo(12.5862f, 12.0939f)
                curveTo(12.3619f, 12.5986f, 12.5892f, 13.1895f, 13.0939f, 13.4138f)
                curveTo(13.5986f, 13.6381f, 14.1895f, 13.4108f, 14.4138f, 12.9061f)
                lineTo(18.4138f, 3.9061f)
                close()
                moveTo(12.7071f, 4.7071f)
                curveTo(13.0976f, 4.3166f, 13.0976f, 3.6834f, 12.7071f, 3.2929f)
                curveTo(12.3166f, 2.9024f, 11.6834f, 2.9024f, 11.2929f, 3.2929f)
                lineTo(9.2929f, 5.2929f)
                curveTo(8.9024f, 5.6834f, 8.9024f, 6.3166f, 9.2929f, 6.7071f)
                lineTo(11.2929f, 8.7071f)
                curveTo(11.6834f, 9.0976f, 12.3166f, 9.0976f, 12.7071f, 8.7071f)
                curveTo(13.0976f, 8.3166f, 13.0976f, 7.6834f, 12.7071f, 7.2929f)
                lineTo(11.4142f, 6.0f)
                lineTo(12.7071f, 4.7071f)
                close()
                moveTo(18.2929f, 7.2929f)
                curveTo(18.6834f, 6.9024f, 19.3166f, 6.9024f, 19.7071f, 7.2929f)
                lineTo(21.7071f, 9.2929f)
                curveTo(22.0976f, 9.6834f, 22.0976f, 10.3166f, 21.7071f, 10.7071f)
                lineTo(19.7071f, 12.7071f)
                curveTo(19.3166f, 13.0976f, 18.6834f, 13.0976f, 18.2929f, 12.7071f)
                curveTo(17.9024f, 12.3166f, 17.9024f, 11.6834f, 18.2929f, 11.2929f)
                lineTo(19.5858f, 10.0f)
                lineTo(18.2929f, 8.7071f)
                curveTo(17.9024f, 8.3166f, 17.9024f, 7.6834f, 18.2929f, 7.2929f)
                close()
                moveTo(7.8789f, 5.0615f)
                curveTo(7.9186f, 5.0582f, 7.959f, 5.0552f, 8.0f, 5.0522f)
                lineTo(8.0f, 3.048f)
                curveTo(7.0195f, 3.1078f, 6.3238f, 3.2424f, 5.7301f, 3.545f)
                curveTo(4.7892f, 4.0243f, 4.0243f, 4.7892f, 3.545f, 5.7301f)
                curveTo(3.0f, 6.7996f, 3.0f, 8.1997f, 3.0f, 11.0f)
                lineTo(3.0f, 13.0f)
                curveTo(3.0f, 15.8003f, 3.0f, 17.2004f, 3.545f, 18.27f)
                curveTo(4.0243f, 19.2108f, 4.7892f, 19.9757f, 5.7301f, 20.455f)
                curveTo(6.7996f, 21.0f, 8.1997f, 21.0f, 11.0f, 21.0f)
                lineTo(13.0f, 21.0f)
                curveTo(15.8003f, 21.0f, 17.2004f, 21.0f, 18.27f, 20.455f)
                curveTo(19.2108f, 19.9757f, 19.9757f, 19.2108f, 20.455f, 18.27f)
                curveTo(20.8514f, 17.492f, 20.9595f, 16.5392f, 20.989f, 15.0f)
                lineTo(18.9886f, 15.0f)
                curveTo(18.98f, 15.4314f, 18.9649f, 15.7978f, 18.9385f, 16.1211f)
                curveTo(18.8805f, 16.8312f, 18.7779f, 17.1561f, 18.673f, 17.362f)
                curveTo(18.3854f, 17.9265f, 17.9265f, 18.3854f, 17.362f, 18.673f)
                curveTo(17.1561f, 18.7779f, 16.8312f, 18.8805f, 16.1211f, 18.9385f)
                curveTo(15.3877f, 18.9984f, 14.4331f, 19.0f, 13.0f, 19.0f)
                lineTo(11.0f, 19.0f)
                curveTo(9.5669f, 19.0f, 8.6123f, 18.9984f, 7.8789f, 18.9385f)
                curveTo(7.1688f, 18.8805f, 6.8439f, 18.7779f, 6.638f, 18.673f)
                curveTo(6.0735f, 18.3854f, 5.6146f, 17.9265f, 5.327f, 17.362f)
                curveTo(5.2221f, 17.1561f, 5.1195f, 16.8312f, 5.0615f, 16.1211f)
                curveTo(5.0016f, 15.3877f, 5.0f, 14.4331f, 5.0f, 13.0f)
                lineTo(5.0f, 11.0f)
                curveTo(5.0f, 9.5669f, 5.0016f, 8.6123f, 5.0615f, 7.8789f)
                curveTo(5.1195f, 7.1688f, 5.2221f, 6.8439f, 5.327f, 6.638f)
                curveTo(5.6146f, 6.0735f, 6.0735f, 5.6146f, 6.638f, 5.327f)
                curveTo(6.8439f, 5.2221f, 7.1688f, 5.1195f, 7.8789f, 5.0615f)
                close()
            }
        }.build().also {
            _codeBlock = it
        }
    }

private var _codeBlock: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun CodeBlockIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcon.CodeBlock,
            contentDescription = null,
    )
}
