@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.CodeBlock: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _codeBlock ?: ImageVector.Builder(
                    name = "CodeBlock",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                ) {
                    moveTo(18.4138f, 3.90614f)
                    curveTo(18.6381f, 3.40146f, 18.4108f, 2.8105f, 17.9061f, 2.58619f)
                    curveTo(17.4015f, 2.36189f, 16.8105f, 2.58918f, 16.5862f, 3.09387f)
                    lineTo(12.5862f, 12.0939f)
                    curveTo(12.3619f, 12.5986f, 12.5892f, 13.1895f, 13.0939f, 13.4138f)
                    curveTo(13.5986f, 13.6381f, 14.1895f, 13.4108f, 14.4138f, 12.9061f)
                    lineTo(18.4138f, 3.90614f)
                    close()
                    moveTo(12.7071f, 4.70711f)
                    curveTo(13.0976f, 4.31658f, 13.0976f, 3.68342f, 12.7071f, 3.29289f)
                    curveTo(12.3166f, 2.90237f, 11.6834f, 2.90237f, 11.2929f, 3.29289f)
                    lineTo(9.29289f, 5.29289f)
                    curveTo(8.90237f, 5.68342f, 8.90237f, 6.31658f, 9.29289f, 6.70711f)
                    lineTo(11.2929f, 8.70711f)
                    curveTo(11.6834f, 9.09763f, 12.3166f, 9.09763f, 12.7071f, 8.70711f)
                    curveTo(13.0976f, 8.31658f, 13.0976f, 7.68342f, 12.7071f, 7.29289f)
                    lineTo(11.4142f, 6.0f)
                    lineTo(12.7071f, 4.70711f)
                    close()
                    moveTo(18.2929f, 7.29289f)
                    curveTo(18.6834f, 6.90237f, 19.3166f, 6.90237f, 19.7071f, 7.29289f)
                    lineTo(21.7071f, 9.29289f)
                    curveTo(22.0976f, 9.68342f, 22.0976f, 10.3166f, 21.7071f, 10.7071f)
                    lineTo(19.7071f, 12.7071f)
                    curveTo(19.3166f, 13.0976f, 18.6834f, 13.0976f, 18.2929f, 12.7071f)
                    curveTo(17.9024f, 12.3166f, 17.9024f, 11.6834f, 18.2929f, 11.2929f)
                    lineTo(19.5858f, 10.0f)
                    lineTo(18.2929f, 8.70711f)
                    curveTo(17.9024f, 8.31658f, 17.9024f, 7.68342f, 18.2929f, 7.29289f)
                    close()
                    moveTo(7.87887f, 5.06148f)
                    curveTo(7.91859f, 5.05823f, 7.95895f, 5.05516f, 8.0f, 5.05225f)
                    lineTo(8.0f, 3.04797f)
                    curveTo(7.01947f, 3.10784f, 6.32382f, 3.24243f, 5.73005f, 3.54497f)
                    curveTo(4.78924f, 4.02433f, 4.02433f, 4.78924f, 3.54497f, 5.73005f)
                    curveTo(3.0f, 6.79961f, 3.0f, 8.19974f, 3.0f, 11.0f)
                    lineTo(3.0f, 13.0f)
                    curveTo(3.0f, 15.8003f, 3.0f, 17.2004f, 3.54497f, 18.27f)
                    curveTo(4.02433f, 19.2108f, 4.78924f, 19.9757f, 5.73005f, 20.455f)
                    curveTo(6.79961f, 21.0f, 8.19974f, 21.0f, 11.0f, 21.0f)
                    lineTo(13.0f, 21.0f)
                    curveTo(15.8003f, 21.0f, 17.2004f, 21.0f, 18.27f, 20.455f)
                    curveTo(19.2108f, 19.9757f, 19.9757f, 19.2108f, 20.455f, 18.27f)
                    curveTo(20.8514f, 17.492f, 20.9595f, 16.5392f, 20.989f, 15.0f)
                    lineTo(18.9886f, 15.0f)
                    curveTo(18.98f, 15.4314f, 18.9649f, 15.7978f, 18.9385f, 16.1211f)
                    curveTo(18.8805f, 16.8312f, 18.7779f, 17.1561f, 18.673f, 17.362f)
                    curveTo(18.3854f, 17.9265f, 17.9265f, 18.3854f, 17.362f, 18.673f)
                    curveTo(17.1561f, 18.7779f, 16.8312f, 18.8805f, 16.1211f, 18.9385f)
                    curveTo(15.3877f, 18.9984f, 14.4331f, 19.0f, 13.0f, 19.0f)
                    lineTo(11.0f, 19.0f)
                    curveTo(9.56687f, 19.0f, 8.6123f, 18.9984f, 7.87887f, 18.9385f)
                    curveTo(7.1688f, 18.8805f, 6.84387f, 18.7779f, 6.63803f, 18.673f)
                    curveTo(6.07354f, 18.3854f, 5.6146f, 17.9265f, 5.32698f, 17.362f)
                    curveTo(5.2221f, 17.1561f, 5.11949f, 16.8312f, 5.06148f, 16.1211f)
                    curveTo(5.00156f, 15.3877f, 5.0f, 14.4331f, 5.0f, 13.0f)
                    lineTo(5.0f, 11.0f)
                    curveTo(5.0f, 9.56687f, 5.00156f, 8.6123f, 5.06148f, 7.87887f)
                    curveTo(5.11949f, 7.1688f, 5.2221f, 6.84387f, 5.32698f, 6.63803f)
                    curveTo(5.6146f, 6.07354f, 6.07354f, 5.6146f, 6.63803f, 5.32698f)
                    curveTo(6.84387f, 5.2221f, 7.1688f, 5.11949f, 7.87887f, 5.06148f)
                    close()
                }
            }.build().also {
                _codeBlock = it
            }
    }


private var _codeBlock: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun CodeBlockIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.CodeBlock.imageVector,
            contentDescription = null,
    )
}
