@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.EmailFilled: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _emailFilled ?: ImageVector.Builder(
                    name = "EmailFilled",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        pathFillType = PathFillType.EvenOdd,
                ) {
                    moveTo(2.436f, 6.184f)
                    curveTo(2.0f, 7.04f, 2.0f, 8.16f, 2.0f, 10.4f)
                    lineTo(2.0f, 13.600000000000001f)
                    curveTo(2.0f, 15.840000000000002f, 2.0f, 16.96f, 2.436f, 17.816000000000003f)
                    arcTo(4.0f, 4.0f, 152.99931737283205f, isMoreThanHalf = false, isPositiveArc = false, 4.184f, 19.564000000000004f)
                    curveTo(5.04f, 20.0f, 6.16f, 20.0f, 8.4f, 20.0f)
                    lineTo(15.600000000000001f, 20.0f)
                    curveTo(17.840000000000003f, 20.0f, 18.96f, 20.0f, 19.816000000000003f, 19.564f)
                    arcTo(4.0f, 4.0f, 62.99931737283203f, isMoreThanHalf = false, isPositiveArc = false, 21.564000000000004f, 17.816f)
                    curveTo(22.0f, 16.96f, 22.0f, 15.84f, 22.0f, 13.6f)
                    lineTo(22.0f, 10.399999999999999f)
                    curveTo(22.0f, 8.159999999999998f, 22.0f, 7.039999999999999f, 21.564f, 6.183999999999998f)
                    arcTo(4.0f, 4.0f, 332.999317372832f, isMoreThanHalf = false, isPositiveArc = false, 19.816f, 4.435999999999998f)
                    curveTo(18.96f, 4.0f, 17.84f, 4.0f, 15.6f, 4.0f)
                    lineTo(8.4f, 4.0f)
                    curveTo(6.16f, 4.0f, 5.040000000000001f, 4.0f, 4.184f, 4.436f)
                    arcTo(4.0f, 4.0f, 242.99931737283202f, isMoreThanHalf = false, isPositiveArc = false, 2.436f, 6.184f)
                    moveTo(5.447f, 9.606f)
                    arcTo(1.0f, 1.0f, 294.7941535026274f, isMoreThanHalf = false, isPositiveArc = false, 4.553f, 11.394f)
                    lineTo(10.658000000000001f, 14.447f)
                    arcTo(3.0f, 3.0f, 116.57272167525814f, isMoreThanHalf = false, isPositiveArc = false, 13.342000000000002f, 14.447f)
                    lineTo(19.447000000000003f, 11.393999999999998f)
                    arcTo(1.0f, 1.0f, 65.20584649737336f, isMoreThanHalf = true, isPositiveArc = false, 18.553000000000004f, 9.605999999999998f)
                    lineTo(12.447000000000005f, 12.657999999999998f)
                    arcTo(1.0f, 1.0f, 63.44863064114032f, isMoreThanHalf = false, isPositiveArc = true, 11.553000000000004f, 12.657999999999998f)
                    close()
                }
            }.build().also {
                _emailFilled = it
            }
    }


private var _emailFilled: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun EmailFilledIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.EmailFilled.imageVector,
            contentDescription = null,
    )
}
