@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.Eraser: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _eraser ?: ImageVector.Builder(
                    name = "Eraser",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        pathFillType = PathFillType.EvenOdd,
                ) {
                    moveTo(14.9f, 2.149f)
                    arcTo(3.0f, 3.0f, 315.0048526342381f, isMoreThanHalf = false, isPositiveArc = false, 10.657f, 2.149f)
                    lineTo(2.879f, 9.927f)
                    arcTo(3.0f, 3.0f, 225.00485263423806f, isMoreThanHalf = false, isPositiveArc = false, 2.879f, 14.17f)
                    lineTo(7.829000000000001f, 19.12f)
                    curveTo(8.428f, 19.719f, 9.218f, 20.011000000000003f, 10.003f, 19.997f)
                    lineTo(10.0f, 20.0f)
                    lineTo(20.0f, 20.0f)
                    lineTo(20.0f, 18.0f)
                    lineTo(13.190000000000001f, 18.0f)
                    lineTo(19.85f, 11.341000000000001f)
                    arcTo(3.0f, 3.0f, 45.00485263423808f, isMoreThanHalf = false, isPositiveArc = false, 19.85f, 7.098000000000001f)
                    close()
                    moveTo(18.435f, 8.513f)
                    lineTo(13.485f, 3.563f)
                    arcTo(1.0f, 1.0f, 314.991348337162f, isMoreThanHalf = false, isPositiveArc = false, 12.071f, 3.563f)
                    lineTo(7.1209999999999996f, 8.513f)
                    lineTo(13.485f, 14.876999999999999f)
                    lineTo(18.435f, 9.927f)
                    arcTo(1.0f, 1.0f, 44.991348337162f, isMoreThanHalf = false, isPositiveArc = false, 18.435f, 8.513f)
                    moveTo(4.293f, 11.34f)
                    lineTo(5.707f, 9.926f)
                    lineTo(12.071f, 16.29f)
                    lineTo(10.657f, 17.704f)
                    arcTo(1.0f, 1.0f, 45.008651662838f, isMoreThanHalf = false, isPositiveArc = true, 9.243f, 17.704f)
                    lineTo(4.293f, 12.754000000000001f)
                    arcTo(1.0f, 1.0f, 135.00865166283802f, isMoreThanHalf = false, isPositiveArc = true, 4.293f, 11.340000000000002f)
                }
            }.build().also {
                _eraser = it
            }
    }


private var _eraser: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun EraserIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.Eraser.imageVector,
            contentDescription = null,
    )
}
