@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.FaceNomouth: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _faceNomouth ?: ImageVector.Builder(
                    name = "FaceNomouth",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                ) {
                    moveTo(12.0002f, 20.0001f)
                    curveTo(7.5892f, 20.0001f, 4.0002f, 16.4111f, 4.0002f, 12.0001f)
                    curveTo(4.0002f, 7.58912f, 7.5892f, 4.00012f, 12.0002f, 4.00012f)
                    curveTo(16.4112f, 4.00012f, 20.0002f, 7.58912f, 20.0002f, 12.0001f)
                    curveTo(20.0002f, 16.4111f, 16.4112f, 20.0001f, 12.0002f, 20.0001f)
                    close()
                    moveTo(12.0002f, 2.00012f)
                    curveTo(6.4772f, 2.00012f, 2.0002f, 6.47812f, 2.0002f, 12.0001f)
                    curveTo(2.0002f, 17.5221f, 6.4772f, 22.0001f, 12.0002f, 22.0001f)
                    curveTo(17.5222f, 22.0001f, 22.0002f, 17.5221f, 22.0002f, 12.0001f)
                    curveTo(22.0002f, 6.47812f, 17.5222f, 2.00012f, 12.0002f, 2.00012f)
                    close()
                    moveTo(8.7863f, 8.98254f)
                    curveTo(7.9413f, 8.98254f, 7.5873f, 9.59254f, 7.5873f, 11.0875f)
                    curveTo(7.5873f, 12.5835f, 7.9413f, 13.1935f, 8.7863f, 13.1935f)
                    curveTo(9.6313f, 13.1935f, 9.9843f, 12.5835f, 9.9843f, 11.0875f)
                    curveTo(9.9843f, 9.59254f, 9.6313f, 8.98254f, 8.7863f, 8.98254f)
                    close()
                    moveTo(14.015f, 11.0875f)
                    curveTo(14.015f, 9.59254f, 14.369f, 8.98254f, 15.214f, 8.98254f)
                    curveTo(16.059f, 8.98254f, 16.412f, 9.59254f, 16.412f, 11.0875f)
                    curveTo(16.412f, 12.5835f, 16.059f, 13.1935f, 15.214f, 13.1935f)
                    curveTo(14.369f, 13.1935f, 14.015f, 12.5835f, 14.015f, 11.0875f)
                    close()
                }
            }.build().also {
                _faceNomouth = it
            }
    }


private var _faceNomouth: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun FaceNomouthIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.FaceNomouth.imageVector,
            contentDescription = null,
    )
}
