@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.FaceAngry: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _faceAngry ?: ImageVector.Builder(
                    name = "FaceAngry",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        pathFillType = PathFillType.EvenOdd,
                ) {
                    moveTo(4.0f, 12.0f)
                    curveTo(4.0f, 16.411f, 7.59f, 20.0f, 12.0f, 20.0f)
                    curveTo(16.41f, 20.0f, 20.0f, 16.411f, 20.0f, 12.0f)
                    curveTo(20.0f, 7.588999999999999f, 16.411f, 4.0f, 12.0f, 4.0f)
                    curveTo(7.588999999999999f, 4.0f, 4.0f, 7.59f, 4.0f, 12.0f)
                    moveTo(2.0f, 12.0f)
                    curveTo(2.0f, 6.478f, 6.477f, 2.0f, 12.0f, 2.0f)
                    curveTo(17.523f, 2.0f, 22.0f, 6.478f, 22.0f, 12.0f)
                    curveTo(22.0f, 17.522f, 17.522f, 22.0f, 12.0f, 22.0f)
                    curveTo(6.4780000000000015f, 22.0f, 2.0f, 17.522f, 2.0f, 12.0f)
                    moveTo(9.818f, 10.926f)
                    lineTo(9.818f, 10.935f)
                    curveTo(9.818f, 12.543000000000001f, 9.437999999999999f, 13.200000000000001f, 8.527999999999999f, 13.200000000000001f)
                    curveTo(7.619999999999998f, 13.200000000000001f, 7.239999999999998f, 12.543000000000001f, 7.239999999999998f, 10.935f)
                    curveTo(7.239999999999998f, 10.405000000000001f, 7.285999999999999f, 9.987f, 7.374999999999998f, 9.653f)
                    lineTo(6.132999999999998f, 9.005f)
                    arcTo(1.0f, 1.0f, 118.38499132873253f, isMoreThanHalf = false, isPositiveArc = true, 7.057999999999998f, 7.232000000000001f)
                    lineTo(10.824999999999998f, 9.196000000000002f)
                    arcTo(1.0f, 1.0f, 296.0389234545689f, isMoreThanHalf = true, isPositiveArc = true, 9.900999999999998f, 10.969000000000001f)
                    close()
                    moveTo(12.006f, 13.708f)
                    lineTo(12.004f, 13.708f)
                    curveTo(9.771999999999998f, 13.708f, 8.666f, 15.034f, 8.363999999999999f, 15.818f)
                    arcTo(0.99f, 0.99f, 200.69123692537556f, isMoreThanHalf = false, isPositiveArc = false, 8.919999999999998f, 17.086f)
                    curveTo(9.419999999999998f, 17.298f, 9.999999999999998f, 17.052999999999997f, 10.221999999999998f, 16.558999999999997f)
                    curveTo(10.260999999999997f, 16.471999999999998f, 10.642999999999997f, 15.708999999999998f, 12.002999999999998f, 15.708999999999998f)
                    lineTo(12.004999999999999f, 15.708999999999998f)
                    curveTo(13.344f, 15.708999999999998f, 13.729999999999999f, 16.453999999999997f, 13.776f, 16.554999999999996f)
                    arcTo(1.0f, 1.0f, 156.9904983131374f, isMoreThanHalf = false, isPositiveArc = false, 15.635f, 15.818999999999996f)
                    curveTo(15.336f, 15.035999999999996f, 14.234f, 13.709999999999996f, 12.006f, 13.708999999999996f)
                    moveTo(16.942f, 7.231999999999996f)
                    arcTo(1.0f, 1.0f, 242.4615404144215f, isMoreThanHalf = false, isPositiveArc = true, 17.867f, 9.005999999999997f)
                    lineTo(16.598000000000003f, 9.666999999999996f)
                    curveTo(16.684f, 9.998999999999997f, 16.729000000000003f, 10.411999999999995f, 16.729000000000003f, 10.934999999999997f)
                    curveTo(16.729000000000003f, 12.544999999999996f, 16.349000000000004f, 13.199999999999998f, 15.440000000000003f, 13.199999999999998f)
                    curveTo(14.533000000000003f, 13.199999999999998f, 14.153000000000002f, 12.544999999999998f, 14.152000000000003f, 10.941999999999997f)
                    lineTo(14.100000000000003f, 10.969999999999997f)
                    arcTo(1.001f, 1.001f, 64.54610319966204f, isMoreThanHalf = false, isPositiveArc = true, 13.175000000000002f, 9.195999999999998f)
                    close()
                }
            }.build().also {
                _faceAngry = it
            }
    }


private var _faceAngry: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun FaceAngryIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.FaceAngry.imageVector,
            contentDescription = null,
    )
}
