@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.FullscreenExit: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _fullscreenExit ?: ImageVector.Builder(
                    name = "FullscreenExit",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                ) {
                    moveTo(15.5002f, 10.0001f)
                    lineTo(21.0002f, 10.0001f)
                    lineTo(21.0002f, 8.00009f)
                    lineTo(16.0002f, 8.00009f)
                    lineTo(16.0002f, 3.00009f)
                    lineTo(14.0002f, 3.00009f)
                    lineTo(14.0002f, 8.50009f)
                    curveTo(14.0002f, 9.32709f, 14.6732f, 10.0001f, 15.5002f, 10.0001f)
                    close()
                    moveTo(14.0002f, 21.0001f)
                    lineTo(16.0002f, 21.0001f)
                    lineTo(16.0002f, 16.0001f)
                    lineTo(21.0002f, 16.0001f)
                    lineTo(21.0002f, 14.0001f)
                    lineTo(15.5002f, 14.0001f)
                    curveTo(14.6732f, 14.0001f, 14.0002f, 14.6731f, 14.0002f, 15.5001f)
                    lineTo(14.0002f, 21.0001f)
                    close()
                    moveTo(10.0002f, 21.0001f)
                    lineTo(8.00018f, 21.0001f)
                    lineTo(8.00018f, 16.0001f)
                    lineTo(3.00018f, 16.0001f)
                    lineTo(3.00018f, 14.0001f)
                    lineTo(8.50018f, 14.0001f)
                    curveTo(9.32718f, 14.0001f, 10.0002f, 14.6731f, 10.0002f, 15.5001f)
                    lineTo(10.0002f, 21.0001f)
                    close()
                    moveTo(3.00018f, 10.0001f)
                    lineTo(8.50018f, 10.0001f)
                    curveTo(9.32718f, 10.0001f, 10.0002f, 9.32709f, 10.0002f, 8.50009f)
                    lineTo(10.0002f, 3.00009f)
                    lineTo(8.00018f, 3.00009f)
                    lineTo(8.00018f, 8.00009f)
                    lineTo(3.00018f, 8.00009f)
                    lineTo(3.00018f, 10.0001f)
                    close()
                }
            }.build().also {
                _fullscreenExit = it
            }
    }


private var _fullscreenExit: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun FullscreenExitIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.FullscreenExit.imageVector,
            contentDescription = null,
    )
}
