@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.HandPoint: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _handPoint ?: ImageVector.Builder(
                    name = "HandPoint",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                        pathFillType = PathFillType.EvenOdd,
                ) {
                    moveTo(4.51f, 12.213f)
                    arcTo(0.5f, 0.5f, 270.0f, isMoreThanHalf = false, isPositiveArc = false, 4.01f, 12.713f)
                    curveTo(4.01f, 12.79f, 4.028f, 12.939f, 4.154999999999999f, 13.066999999999998f)
                    lineTo(9.625f, 18.534999999999997f)
                    arcTo(4.96f, 4.96f, 135.2001621523252f, isMoreThanHalf = false, isPositiveArc = false, 13.16f, 20.0f)
                    lineTo(13.937f, 20.0f)
                    arcTo(4.98f, 4.98f, 90.16779194577458f, isMoreThanHalf = false, isPositiveArc = false, 18.58f, 16.858f)
                    curveTo(18.857999999999997f, 16.16f, 19.0f, 15.427f, 19.0f, 14.677f)
                    lineTo(19.0f, 14.0f)
                    curveTo(19.0f, 13.171f, 18.478f, 12.419f, 17.701999999999998f, 12.128f)
                    lineTo(10.0f, 9.225f)
                    lineTo(10.0f, 3.5f)
                    arcTo(0.5f, 0.5f, 0.0f, isMoreThanHalf = false, isPositiveArc = false, 9.0f, 3.5f)
                    lineTo(9.0f, 13.841f)
                    curveTo(9.0f, 14.286f, 8.734f, 14.684999999999999f, 8.323f, 14.856f)
                    curveTo(7.9110000000000005f, 15.028f, 7.441000000000001f, 14.936f, 7.1240000000000006f, 14.621f)
                    lineTo(4.864000000000001f, 12.359f)
                    arcTo(0.5f, 0.5f, 314.9281577971533f, isMoreThanHalf = false, isPositiveArc = false, 4.509f, 12.213f)
                    moveTo(13.936f, 22.0f)
                    lineTo(13.159f, 22.0f)
                    arcTo(6.95f, 6.95f, 89.8331863744008f, isMoreThanHalf = false, isPositiveArc = true, 8.209f, 19.948999999999998f)
                    lineTo(2.7399999999999993f, 14.480999999999998f)
                    arcTo(2.49f, 2.49f, 134.91220018996913f, isMoreThanHalf = false, isPositiveArc = true, 2.007999999999999f, 12.712999999999997f)
                    curveTo(2.007999999999999f, 12.043999999999997f, 2.267999999999999f, 11.415999999999997f, 2.740999999999999f, 10.943999999999997f)
                    arcTo(2.505f, 2.505f, 225.1390720932247f, isMoreThanHalf = false, isPositiveArc = true, 6.276f, 10.944999999999997f)
                    lineTo(6.999f, 11.667999999999997f)
                    lineTo(6.999f, 3.5f)
                    curveTo(7.0f, 2.121f, 8.121f, 1.0f, 9.5f, 1.0f)
                    curveTo(10.878f, 1.0f, 12.0f, 2.121f, 12.0f, 3.5f)
                    lineTo(12.0f, 7.842f)
                    lineTo(18.405f, 10.256f)
                    arcTo(4.02f, 4.02f, 290.7610069767078f, isMoreThanHalf = false, isPositiveArc = true, 21.0f, 14.0f)
                    lineTo(21.0f, 14.677f)
                    curveTo(21.0f, 15.683f, 20.81f, 16.666f, 20.436f, 17.6f)
                    arcTo(6.97f, 6.97f, 21.636632734020917f, isMoreThanHalf = false, isPositiveArc = true, 13.937000000000001f, 22.0f)
                }
            }.build().also {
                _handPoint = it
            }
    }


private var _handPoint: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun HandPointIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.HandPoint.imageVector,
            contentDescription = null,
    )
}
