@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.Home: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _home ?: ImageVector.Builder(
                    name = "Home",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                        pathFillType = PathFillType.EvenOdd,
                ) {
                    moveTo(12.614f, 2.477f)
                    arcTo(1.0f, 1.0f, 307.87929439406173f, isMoreThanHalf = false, isPositiveArc = false, 11.386000000000001f, 2.477f)
                    lineTo(3.772f, 8.4f)
                    arcTo(2.0f, 2.0f, 232.12072307627952f, isMoreThanHalf = false, isPositiveArc = false, 3.0f, 9.98f)
                    lineTo(3.0f, 20.0f)
                    arcTo(1.0f, 1.0f, 180.0f, isMoreThanHalf = false, isPositiveArc = false, 4.0f, 21.0f)
                    lineTo(10.0f, 21.0f)
                    arcTo(1.0f, 1.0f, 90.0f, isMoreThanHalf = false, isPositiveArc = false, 11.0f, 20.0f)
                    lineTo(11.0f, 15.0f)
                    arcTo(1.0f, 1.0f, 180.0f, isMoreThanHalf = true, isPositiveArc = true, 13.0f, 15.0f)
                    lineTo(13.0f, 20.0f)
                    arcTo(1.0f, 1.0f, 180.0f, isMoreThanHalf = false, isPositiveArc = false, 14.0f, 21.0f)
                    lineTo(20.0f, 21.0f)
                    arcTo(1.0f, 1.0f, 90.0f, isMoreThanHalf = false, isPositiveArc = false, 21.0f, 20.0f)
                    lineTo(21.0f, 9.978f)
                    arcTo(2.0f, 2.0f, 0.011113150480514259f, isMoreThanHalf = false, isPositiveArc = false, 20.228f, 8.399f)
                    close()
                    moveTo(9.0f, 19.0f)
                    lineTo(9.0f, 15.0f)
                    arcTo(3.0f, 3.0f, 180.0f, isMoreThanHalf = true, isPositiveArc = true, 15.0f, 15.0f)
                    lineTo(15.0f, 19.0f)
                    lineTo(19.0f, 19.0f)
                    lineTo(19.0f, 9.978f)
                    lineTo(12.0f, 4.534f)
                    lineTo(5.0f, 10.0f)
                    lineTo(5.0f, 19.0f)
                    close()
                }
            }.build().also {
                _home = it
            }
    }


private var _home: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun HomeIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.Home.imageVector,
            contentDescription = null,
    )
}
