@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.Hourglass2: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _hourglass2 ?: ImageVector.Builder(
                    name = "Hourglass2",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                        pathFillType = PathFillType.EvenOdd,
                ) {
                    moveTo(17.0f, 6.553f)
                    curveTo(17.0f, 6.933f, 16.855f, 7.307f, 16.582f, 7.631f)
                    lineTo(13.687000000000001f, 11.07f)
                    arcTo(1.44f, 1.44f, 220.2803198754455f, isMoreThanHalf = false, isPositiveArc = false, 13.687000000000001f, 12.932f)
                    lineTo(16.583000000000002f, 16.369f)
                    curveTo(16.855f, 16.694f, 17.000000000000004f, 17.066f, 17.000000000000004f, 17.448f)
                    lineTo(17.000000000000004f, 20.0f)
                    lineTo(7.0f, 20.0f)
                    lineTo(7.0f, 17.448f)
                    curveTo(7.0f, 17.067f, 7.145f, 16.694f, 7.418f, 16.368000000000002f)
                    lineTo(10.313f, 12.931000000000003f)
                    arcTo(1.44f, 1.44f, 40.280319875445535f, isMoreThanHalf = false, isPositiveArc = false, 10.313f, 11.069000000000003f)
                    lineTo(7.418f, 7.63f)
                    curveTo(7.145f, 7.307f, 7.0f, 6.934f, 7.0f, 6.55f)
                    lineTo(7.0f, 4.0f)
                    lineTo(17.0f, 4.0f)
                    close()
                    moveTo(19.0f, 6.553f)
                    lineTo(19.0f, 4.0f)
                    curveTo(19.0f, 2.8979999999999997f, 18.103f, 2.0f, 17.0f, 2.0f)
                    lineTo(7.0f, 2.0f)
                    curveTo(5.897f, 2.0f, 5.0f, 2.898f, 5.0f, 4.0f)
                    lineTo(5.0f, 6.552f)
                    curveTo(5.0f, 7.411f, 5.307f, 8.23f, 5.888f, 8.92f)
                    lineTo(8.482f, 12.0f)
                    lineTo(5.89f, 15.08f)
                    curveTo(5.307f, 15.77f, 5.0f, 16.589f, 5.0f, 17.448f)
                    lineTo(5.0f, 20.0f)
                    curveTo(5.0f, 21.103f, 5.897f, 22.0f, 7.0f, 22.0f)
                    lineTo(17.0f, 22.0f)
                    curveTo(18.103f, 22.0f, 19.0f, 21.103f, 19.0f, 20.0f)
                    lineTo(19.0f, 17.448f)
                    curveTo(19.0f, 16.6f, 18.684f, 15.758000000000001f, 18.112f, 15.08f)
                    lineTo(15.518f, 12.0f)
                    lineTo(18.111f, 8.92f)
                    curveTo(18.693f, 8.23f, 19.001f, 7.41f, 19.001f, 6.553f)
                    moveTo(16.227f, 6.5f)
                    lineTo(7.772f, 6.5f)
                    lineTo(8.465f, 7.322f)
                    lineTo(11.235f, 10.611f)
                    arcTo(0.997f, 0.997f, 140.1122167357628f, isMoreThanHalf = false, isPositiveArc = false, 12.764999999999999f, 10.611f)
                    lineTo(15.534999999999998f, 7.322000000000001f)
                    close()
                    moveTo(10.568999999999999f, 15.39f)
                    curveTo(10.991f, 15.094000000000001f, 11.485f, 14.940000000000001f, 12.0f, 14.940000000000001f)
                    curveTo(12.514f, 14.940000000000001f, 13.01f, 15.095f, 13.431000000000001f, 15.39f)
                    curveTo(15.72f, 16.990000000000002f, 15.97f, 17.164f, 15.997f, 17.368000000000002f)
                    quadTo(16.001f, 17.404000000000003f, 16.0f, 17.448f)
                    lineTo(16.0f, 19.0f)
                    lineTo(8.0f, 19.0f)
                    lineTo(8.0f, 17.448f)
                    quadTo(7.999f, 17.404f, 8.004f, 17.368000000000002f)
                    curveTo(8.030999999999999f, 17.164f, 8.280999999999999f, 16.990000000000002f, 10.568999999999999f, 15.390000000000002f)
                }
            }.build().also {
                _hourglass2 = it
            }
    }


private var _hourglass2: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun Hourglass2IconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.Hourglass2.imageVector,
            contentDescription = null,
    )
}
