@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.InfoFilled: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _infoFilled ?: ImageVector.Builder(
                    name = "InfoFilled",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                ) {
                    moveTo(11.9997f, 9.00011f)
                    curveTo(11.1717f, 9.00011f, 10.4997f, 8.32811f, 10.4997f, 7.50011f)
                    curveTo(10.4997f, 6.67111f, 11.1717f, 6.00011f, 11.9997f, 6.00011f)
                    curveTo(12.8287f, 6.00011f, 13.4997f, 6.67111f, 13.4997f, 7.50011f)
                    curveTo(13.4997f, 8.32811f, 12.8287f, 9.00011f, 11.9997f, 9.00011f)
                    close()
                    moveTo(10.9997f, 18.0001f)
                    lineTo(12.9997f, 18.0001f)
                    lineTo(12.9997f, 10.0001f)
                    lineTo(10.9997f, 10.0001f)
                    lineTo(10.9997f, 18.0001f)
                    close()
                    moveTo(11.9997f, 2.00011f)
                    curveTo(6.48569f, 2.00011f, 1.99969f, 6.48611f, 1.99969f, 12.0001f)
                    curveTo(1.99969f, 17.5141f, 6.48569f, 22.0001f, 11.9997f, 22.0001f)
                    curveTo(17.5147f, 22.0001f, 21.9997f, 17.5141f, 21.9997f, 12.0001f)
                    curveTo(21.9997f, 6.48611f, 17.5147f, 2.00011f, 11.9997f, 2.00011f)
                    close()
                }
            }.build().also {
                _infoFilled = it
            }
    }


private var _infoFilled: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun InfoFilledIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.InfoFilled.imageVector,
            contentDescription = null,
    )
}
