@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.Kakao: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _kakao ?: ImageVector.Builder(
                    name = "Kakao",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                ) {
                    moveTo(6.05f, 13.295f)
                    curveTo(6.16f, 13.398f, 6.306f, 13.455f, 6.457f, 13.451f)
                    arcTo(0.566f, 0.566f, 90.01511480177776f, isMoreThanHalf = false, isPositiveArc = false, 7.023f, 12.898f)
                    lineTo(7.023f, 9.445f)
                    lineTo(7.941f, 9.445f)
                    arcTo(0.566f, 0.566f, 89.99999905775272f, isMoreThanHalf = false, isPositiveArc = false, 7.941f, 8.313f)
                    lineTo(4.966f, 8.313f)
                    arcTo(0.566f, 0.566f, 270.0000009422473f, isMoreThanHalf = true, isPositiveArc = false, 4.966f, 9.445f)
                    lineTo(5.872f, 9.445f)
                    lineTo(5.872f, 12.898f)
                    curveTo(5.877f, 13.048f, 5.941f, 13.190999999999999f, 6.05f, 13.294f)
                    moveTo(12.776f, 13.335f)
                    arcTo(0.5f, 0.5f, 111.46468119497878f, isMoreThanHalf = false, isPositiveArc = false, 12.985f, 13.369000000000002f)
                    lineTo(14.872f, 13.363000000000001f)
                    arcTo(0.535f, 0.535f, 96.55740203003279f, isMoreThanHalf = true, isPositiveArc = false, 14.872f, 12.3f)
                    lineTo(13.614f, 12.3f)
                    lineTo(13.614f, 8.891f)
                    arcTo(0.591f, 0.591f, 0.0f, isMoreThanHalf = false, isPositiveArc = false, 12.432f, 8.891f)
                    lineTo(12.432f, 12.841000000000001f)
                    arcTo(0.535f, 0.535f, 179.38357472609013f, isMoreThanHalf = false, isPositiveArc = false, 12.776f, 13.335f)
                    moveTo(15.802f, 13.278f)
                    curveTo(15.91f, 13.387f, 16.058f, 13.449f, 16.212f, 13.451f)
                    lineTo(16.212f, 13.445f)
                    curveTo(16.365f, 13.444f, 16.512f, 13.383000000000001f, 16.62f, 13.275f)
                    arcTo(0.63f, 0.63f, 43.126244462254924f, isMoreThanHalf = false, isPositiveArc = false, 16.790000000000003f, 12.860000000000001f)
                    lineTo(16.790000000000003f, 11.602f)
                    lineTo(16.991000000000003f, 11.401f)
                    lineTo(18.356f, 13.206f)
                    arcTo(0.55f, 0.55f, 143.93529410878864f, isMoreThanHalf = false, isPositiveArc = false, 18.816000000000003f, 13.432f)
                    arcTo(0.54f, 0.54f, 92.21976857917994f, isMoreThanHalf = false, isPositiveArc = false, 19.168000000000003f, 13.319f)
                    arcTo(0.6f, 0.6f, 52.31399692605764f, isMoreThanHalf = false, isPositiveArc = false, 19.318f, 13.149000000000001f)
                    arcTo(0.6f, 0.6f, 30.4607554638519f, isMoreThanHalf = false, isPositiveArc = false, 19.394000000000002f, 12.935f)
                    arcTo(0.56f, 0.56f, 8.404152233310285f, isMoreThanHalf = false, isPositiveArc = false, 19.281000000000002f, 12.508000000000001f)
                    lineTo(17.853f, 10.621f)
                    lineTo(19.173000000000002f, 9.294f)
                    arcTo(0.44f, 0.44f, 46.01399497117912f, isMoreThanHalf = false, isPositiveArc = false, 19.306f, 8.942f)
                    arcTo(0.56f, 0.56f, 355.4678659442702f, isMoreThanHalf = false, isPositiveArc = false, 19.130000000000003f, 8.577f)
                    arcTo(0.55f, 0.55f, 317.16326210540586f, isMoreThanHalf = false, isPositiveArc = false, 18.734f, 8.401f)
                    arcTo(0.45f, 0.45f, 270.33060337561824f, isMoreThanHalf = false, isPositiveArc = false, 18.413f, 8.533f)
                    lineTo(16.79f, 10.149f)
                    lineTo(16.79f, 8.891f)
                    arcTo(0.579f, 0.579f, 357.6186972763694f, isMoreThanHalf = false, isPositiveArc = false, 15.633f, 8.891f)
                    lineTo(15.633f, 12.866f)
                    curveTo(15.633f, 13.02f, 15.693f, 13.168f, 15.802f, 13.278f)
                }

                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        pathFillType = PathFillType.EvenOdd,
                ) {
                    moveTo(11.263f, 13.397f)
                    arcTo(0.5f, 0.5f, 117.52613771382792f, isMoreThanHalf = false, isPositiveArc = false, 11.545f, 13.451f)
                    lineTo(11.545f, 13.445f)
                    arcTo(1.0f, 1.0f, 88.42694079762327f, isMoreThanHalf = false, isPositiveArc = false, 11.915f, 13.363f)
                    curveTo(12.055f, 13.288f, 12.229999999999999f, 13.086f, 12.055f, 12.539f)
                    lineTo(10.665f, 8.885f)
                    arcTo(0.81f, 0.81f, 342.8537900011082f, isMoreThanHalf = false, isPositiveArc = false, 9.116999999999999f, 8.885f)
                    lineTo(7.726999999999999f, 12.539f)
                    curveTo(7.550999999999999f, 13.086f, 7.701999999999999f, 13.288f, 7.864999999999999f, 13.363f)
                    quadTo(8.042f, 13.443f, 8.237f, 13.445f)
                    arcTo(0.47f, 0.47f, 96.94187054510273f, isMoreThanHalf = false, isPositiveArc = false, 8.715f, 13.187000000000001f)
                    lineTo(9.004f, 12.432f)
                    lineTo(10.796f, 12.432f)
                    lineTo(11.059999999999999f, 13.193f)
                    arcTo(0.5f, 0.5f, 151.86666743949604f, isMoreThanHalf = false, isPositiveArc = false, 11.262999999999998f, 13.397f)
                    moveTo(9.89f, 9.765f)
                    lineTo(10.468f, 11.413f)
                    lineTo(9.312f, 11.413f)
                    close()
                    moveTo(5.25f, 22.29f)
                    curveTo(5.442f, 22.4f, 5.659f, 22.46f, 5.88f, 22.46f)
                    quadTo(6.052f, 22.458000000000002f, 6.22f, 22.42f)
                    curveTo(6.4799999999999995f, 22.360000000000003f, 7.06f, 22.090000000000003f, 10.48f, 19.69f)
                    curveTo(11.0f, 19.77f, 11.49f, 19.77f, 12.0f, 19.77f)
                    curveTo(18.07f, 19.77f, 23.0f, 15.78f, 23.0f, 10.889999999999999f)
                    curveTo(23.0f, 5.999999999999998f, 18.07f, 2.0f, 12.0f, 2.0f)
                    curveTo(5.93f, 2.0f, 1.0f, 6.0f, 1.0f, 10.89f)
                    arcTo(8.43f, 8.43f, 178.16348874751918f, isMoreThanHalf = false, isPositiveArc = false, 5.5f, 18.080000000000002f)
                    arcTo(31.0f, 31.0f, 198.1627158999966f, isMoreThanHalf = false, isPositiveArc = false, 4.68f, 21.080000000000002f)
                    arcTo(1.22f, 1.22f, 188.01764120282203f, isMoreThanHalf = false, isPositiveArc = false, 5.25f, 22.290000000000003f)
                    moveTo(3.0f, 10.89f)
                    curveTo(3.0f, 7.09f, 7.0f, 4.0f, 12.0f, 4.0f)
                    curveTo(17.0f, 4.0f, 21.03f, 7.1f, 21.03f, 10.89f)
                    curveTo(21.03f, 14.680000000000001f, 17.03f, 17.77f, 12.030000000000001f, 17.77f)
                    arcTo(13.0f, 13.0f, 90.21268324955915f, isMoreThanHalf = false, isPositiveArc = true, 10.39f, 17.66f)
                    lineTo(10.0f, 17.6f)
                    lineTo(9.65f, 17.830000000000002f)
                    lineTo(7.16f, 19.55f)
                    quadTo(7.289f, 19.09f, 7.445f, 18.552f)
                    lineTo(7.65f, 17.84f)
                    lineTo(7.880000000000001f, 17.04f)
                    lineTo(7.130000000000001f, 16.669999999999998f)
                    curveTo(4.54f, 15.39f, 3.0f, 13.23f, 3.0f, 10.89f)
                }
            }.build().also {
                _kakao = it
            }
    }


private var _kakao: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun KakaoIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.Kakao.imageVector,
            contentDescription = null,
    )
}
