@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.MapPin: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _mapPin ?: ImageVector.Builder(
                    name = "MapPin",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        pathFillType = PathFillType.EvenOdd,
                ) {
                    moveTo(12.0f, 12.732f)
                    arcTo(3.214f, 3.214f, 90.0f, isMoreThanHalf = true, isPositiveArc = true, 12.0f, 6.303999999999999f)
                    arcTo(3.214f, 3.214f, 270.0f, isMoreThanHalf = false, isPositiveArc = true, 12.0f, 12.732f)
                    moveTo(18.256999999999998f, 5.331999999999999f)
                    arcTo(7.54f, 7.54f, 326.07558434306037f, isMoreThanHalf = false, isPositiveArc = false, 5.743999999999998f, 5.331999999999999f)
                    curveTo(3.982999999999998f, 7.904999999999999f, 4.1469999999999985f, 11.344999999999999f, 5.889999999999998f, 13.931f)
                    lineTo(11.556999999999999f, 22.339f)
                    arcTo(0.534f, 0.534f, 146.2490782230518f, isMoreThanHalf = false, isPositiveArc = false, 12.444999999999999f, 22.339f)
                    lineTo(18.110999999999997f, 13.931f)
                    curveTo(19.853999999999996f, 11.344999999999999f, 20.019f, 7.904999999999999f, 18.256999999999998f, 5.331999999999999f)
                }
            }.build().also {
                _mapPin = it
            }
    }


private var _mapPin: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun MapPinIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.MapPin.imageVector,
            contentDescription = null,
    )
}
