@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.NotificationImportant: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _notificationImportant ?: ImageVector.Builder(
                    name = "NotificationImportant",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                ) {
                    moveTo(19.9998f, 6.0f)
                    curveTo(19.9998f, 6.55228f, 20.448f, 7.0f, 21.0003f, 7.0f)
                    curveTo(21.5526f, 7.0f, 22.0008f, 6.55228f, 22.0008f, 6.0f)
                    lineTo(22.0008f, 1.0f)
                    curveTo(22.0008f, 0.447715f, 21.5526f, 0.0f, 21.0003f, 0.0f)
                    curveTo(20.448f, 0.0f, 19.9998f, 0.447715f, 19.9998f, 1.0f)
                    lineTo(19.9998f, 6.0f)
                    close()
                    moveTo(21.0f, 10.9f)
                    curveTo(21.663f, 10.9f, 22.2f, 10.363f, 22.2f, 9.7f)
                    curveTo(22.2f, 9.037f, 21.663f, 8.5f, 21.0f, 8.5f)
                    curveTo(20.337f, 8.5f, 19.8f, 9.037f, 19.8f, 9.7f)
                    curveTo(19.8f, 10.363f, 20.337f, 10.9f, 21.0f, 10.9f)
                    close()
                    moveTo(6.29472f, 13.6021f)
                    lineTo(4.80072f, 16.0001f)
                    lineTo(19.1987f, 16.0001f)
                    lineTo(17.7057f, 13.6021f)
                    curveTo(16.6837f, 11.9631f, 16.1447f, 10.0761f, 16.1447f, 8.14512f)
                    curveTo(16.1447f, 5.85912f, 14.2847f, 4.00012f, 11.9997f, 4.00012f)
                    curveTo(9.71472f, 4.00012f, 7.85472f, 5.85912f, 7.85472f, 8.14512f)
                    curveTo(7.85472f, 10.0751f, 7.31572f, 11.9621f, 6.29472f, 13.6021f)
                    close()
                    moveTo(9.99969f, 18.0001f)
                    curveTo(9.99969f, 19.1031f, 10.8967f, 20.0001f, 11.9997f, 20.0001f)
                    curveTo(13.1027f, 20.0001f, 13.9997f, 19.1031f, 13.9997f, 18.0001f)
                    lineTo(9.99969f, 18.0001f)
                    close()
                    moveTo(18.1447f, 8.14512f)
                    curveTo(18.1447f, 9.70212f, 18.5797f, 11.2231f, 19.4027f, 12.5441f)
                    lineTo(21.7537f, 16.3181f)
                    curveTo(21.9647f, 16.6561f, 21.9757f, 17.0831f, 21.7817f, 17.4331f)
                    curveTo(21.5887f, 17.7831f, 21.2197f, 18.0001f, 20.8197f, 18.0001f)
                    lineTo(15.9997f, 18.0001f)
                    curveTo(15.9997f, 20.2061f, 14.2057f, 22.0001f, 11.9997f, 22.0001f)
                    curveTo(9.79471f, 22.0001f, 7.99971f, 20.2061f, 7.99971f, 18.0001f)
                    lineTo(3.17971f, 18.0001f)
                    curveTo(2.77971f, 18.0001f, 2.41171f, 17.7831f, 2.21771f, 17.4331f)
                    curveTo(2.02471f, 17.0841f, 2.03471f, 16.6571f, 2.24671f, 16.3181f)
                    lineTo(4.59671f, 12.5441f)
                    curveTo(5.41971f, 11.2231f, 5.85471f, 9.70112f, 5.85471f, 8.14512f)
                    curveTo(5.85471f, 4.75612f, 8.61171f, 2.00012f, 11.9997f, 2.00012f)
                    curveTo(15.3877f, 2.00012f, 18.1447f, 4.75612f, 18.1447f, 8.14512f)
                    close()
                }
            }.build().also {
                _notificationImportant = it
            }
    }


private var _notificationImportant: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun NotificationImportantIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.NotificationImportant.imageVector,
            contentDescription = null,
    )
}
