@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.OpenInNew: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _openInNew ?: ImageVector.Builder(
                    name = "OpenInNew",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                ) {
                    moveTo(10.3572f, 3.0f)
                    lineTo(12.0f, 3.0f)
                    lineTo(12.0f, 5.0f)
                    lineTo(10.4f, 5.0f)
                    curveTo(9.26341f, 5.0f, 8.4711f, 5.00078f, 7.85426f, 5.05118f)
                    curveTo(7.24909f, 5.10062f, 6.9014f, 5.19279f, 6.63804f, 5.32698f)
                    curveTo(6.07356f, 5.6146f, 5.61462f, 6.07354f, 5.327f, 6.63803f)
                    curveTo(5.19281f, 6.90138f, 5.10064f, 7.24907f, 5.05119f, 7.85424f)
                    curveTo(5.00079f, 8.47108f, 5.00002f, 9.26339f, 5.00002f, 10.4f)
                    lineTo(5.00002f, 13.6f)
                    curveTo(5.00002f, 14.7366f, 5.00079f, 15.5289f, 5.05119f, 16.1458f)
                    curveTo(5.10064f, 16.7509f, 5.19281f, 17.0986f, 5.327f, 17.362f)
                    curveTo(5.61462f, 17.9265f, 6.07356f, 18.3854f, 6.63804f, 18.673f)
                    curveTo(6.9014f, 18.8072f, 7.24909f, 18.8994f, 7.85426f, 18.9488f)
                    curveTo(8.4711f, 18.9992f, 9.26341f, 19.0f, 10.4f, 19.0f)
                    lineTo(13.6f, 19.0f)
                    curveTo(14.7366f, 19.0f, 15.5289f, 18.9992f, 16.1458f, 18.9488f)
                    curveTo(16.7509f, 18.8994f, 17.0986f, 18.8072f, 17.362f, 18.673f)
                    curveTo(17.9265f, 18.3854f, 18.3854f, 17.9265f, 18.673f, 17.362f)
                    curveTo(18.8072f, 17.0986f, 18.8994f, 16.7509f, 18.9488f, 16.1458f)
                    curveTo(18.9992f, 15.5289f, 19.0f, 14.7366f, 19.0f, 13.6f)
                    lineTo(19.0f, 12.0f)
                    lineTo(21.0f, 12.0f)
                    lineTo(21.0f, 13.6428f)
                    curveTo(21.0f, 14.7266f, 21.0f, 15.6008f, 20.9422f, 16.3086f)
                    curveTo(20.8826f, 17.0375f, 20.7568f, 17.6777f, 20.455f, 18.27f)
                    curveTo(19.9757f, 19.2108f, 19.2108f, 19.9757f, 18.27f, 20.455f)
                    curveTo(17.6777f, 20.7568f, 17.0375f, 20.8826f, 16.3086f, 20.9422f)
                    curveTo(15.6008f, 21.0f, 14.7266f, 21.0f, 13.6428f, 21.0f)
                    lineTo(10.3572f, 21.0f)
                    curveTo(9.27341f, 21.0f, 8.39927f, 21.0f, 7.69139f, 20.9422f)
                    curveTo(6.96254f, 20.8826f, 6.32235f, 20.7568f, 5.73006f, 20.455f)
                    curveTo(4.78925f, 19.9757f, 4.02435f, 19.2108f, 3.54498f, 18.27f)
                    curveTo(3.2432f, 17.6777f, 3.11738f, 17.0375f, 3.05783f, 16.3086f)
                    curveTo(3.0f, 15.6007f, 3.00001f, 14.7266f, 3.00002f, 13.6428f)
                    lineTo(3.00002f, 10.3572f)
                    curveTo(3.00001f, 9.27341f, 3.0f, 8.39926f, 3.05783f, 7.69138f)
                    curveTo(3.11738f, 6.96253f, 3.2432f, 6.32234f, 3.54498f, 5.73005f)
                    curveTo(4.02435f, 4.78924f, 4.78925f, 4.02433f, 5.73006f, 3.54497f)
                    curveTo(6.32235f, 3.24318f, 6.96254f, 3.11737f, 7.69139f, 3.05782f)
                    curveTo(8.39927f, 2.99998f, 9.27342f, 2.99999f, 10.3572f, 3.0f)
                    close()
                }

                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                ) {
                    moveTo(20.8083f, 8.58819f)
                    curveTo(21.0f, 8.36376f, 21.0f, 7.87911f, 21.0f, 6.90981f)
                    lineTo(21.0f, 4.6f)
                    curveTo(21.0f, 4.03996f, 21.0f, 3.75992f, 20.891f, 3.54601f)
                    curveTo(20.7951f, 3.35785f, 20.6421f, 3.20487f, 20.454f, 3.10899f)
                    curveTo(20.2401f, 3.0f, 19.96f, 3.0f, 19.4f, 3.0f)
                    lineTo(17.0902f, 3.0f)
                    curveTo(16.1209f, 3.0f, 15.6362f, 3.0f, 15.4118f, 3.19168f)
                    curveTo(15.2171f, 3.35799f, 15.1137f, 3.60747f, 15.1338f, 3.86277f)
                    curveTo(15.157f, 4.15699f, 15.4997f, 4.49969f, 16.1851f, 5.1851f)
                    lineTo(16.7929f, 5.7929f)
                    lineTo(11.7929f, 10.7929f)
                    curveTo(11.4024f, 11.1834f, 11.4024f, 11.8166f, 11.7929f, 12.2071f)
                    curveTo(12.1834f, 12.5976f, 12.8166f, 12.5976f, 13.2071f, 12.2071f)
                    lineTo(18.2071f, 7.20711f)
                    lineTo(18.8149f, 7.8149f)
                    curveTo(19.5003f, 8.50031f, 19.843f, 8.84301f, 20.1372f, 8.86616f)
                    curveTo(20.3925f, 8.88625f, 20.642f, 8.78292f, 20.8083f, 8.58819f)
                    close()
                }
            }.build().also {
                _openInNew = it
            }
    }


private var _openInNew: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun OpenInNewIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.OpenInNew.imageVector,
            contentDescription = null,
    )
}
