@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.PersonRemove: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _personRemove ?: ImageVector.Builder(
                    name = "PersonRemove",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                ) {
                    moveTo(10.99f, 10.2001f)
                    curveTo(11.8734f, 10.2001f, 12.59f, 9.48356f, 12.59f, 8.60013f)
                    curveTo(12.59f, 7.7167f, 11.8734f, 7.00013f, 10.99f, 7.00013f)
                    curveTo(10.1066f, 7.00013f, 9.38998f, 7.7167f, 9.38998f, 8.60013f)
                    curveTo(9.38998f, 9.48356f, 10.1066f, 10.2001f, 10.99f, 10.2001f)
                    close()
                    moveTo(14.59f, 8.60013f)
                    curveTo(14.59f, 10.5881f, 12.978f, 12.2001f, 10.99f, 12.2001f)
                    curveTo(9.00198f, 12.2001f, 7.38998f, 10.5881f, 7.38998f, 8.60013f)
                    curveTo(7.38998f, 6.61213f, 9.00198f, 5.00013f, 10.99f, 5.00013f)
                    curveTo(12.978f, 5.00013f, 14.59f, 6.61213f, 14.59f, 8.60013f)
                    close()
                    moveTo(4.99798f, 20.6884f)
                    lineTo(4.99815f, 20.6851f)
                    lineTo(4.99798f, 20.6884f)
                    close()
                    moveTo(5.33109f, 19.0001f)
                    curveTo(6.15449f, 16.6703f, 8.37772f, 15.0001f, 10.9896f, 15.0001f)
                    curveTo(13.6019f, 15.0001f, 15.8249f, 16.6702f, 16.6486f, 19.0001f)
                    lineTo(5.33109f, 19.0001f)
                    close()
                    moveTo(18.9792f, 20.5825f)
                    curveTo(18.7616f, 16.3585f, 15.268f, 13.0001f, 10.9896f, 13.0001f)
                    curveTo(6.71198f, 13.0001f, 3.21758f, 16.3585f, 3.00078f, 20.5825f)
                    curveTo(2.98878f, 20.8089f, 3.17918f, 21.0001f, 3.40638f, 21.0001f)
                    lineTo(18.5736f, 21.0001f)
                    curveTo(18.8008f, 21.0001f, 18.9904f, 20.8089f, 18.9792f, 20.5825f)
                    close()
                    moveTo(20.9067f, 9.72663f)
                    curveTo(21.2712f, 10.0911f, 21.8621f, 10.0911f, 22.2266f, 9.72663f)
                    curveTo(22.5911f, 9.36214f, 22.5911f, 8.77119f, 22.2266f, 8.4067f)
                    lineTo(20.3199f, 6.5f)
                    lineTo(22.2266f, 4.5933f)
                    curveTo(22.5911f, 4.22881f, 22.5911f, 3.63786f, 22.2266f, 3.27337f)
                    curveTo(21.8621f, 2.90888f, 21.2712f, 2.90888f, 20.9067f, 3.27337f)
                    lineTo(19.0f, 5.18007f)
                    lineTo(17.0933f, 3.27337f)
                    curveTo(16.7288f, 2.90888f, 16.1379f, 2.90888f, 15.7734f, 3.27337f)
                    curveTo(15.4089f, 3.63786f, 15.4089f, 4.22881f, 15.7734f, 4.5933f)
                    lineTo(17.6801f, 6.5f)
                    lineTo(15.7734f, 8.4067f)
                    curveTo(15.4089f, 8.77119f, 15.4089f, 9.36214f, 15.7734f, 9.72663f)
                    curveTo(16.1379f, 10.0911f, 16.7288f, 10.0911f, 17.0933f, 9.72663f)
                    lineTo(19.0f, 7.81993f)
                    lineTo(20.9067f, 9.72663f)
                    close()
                }
            }.build().also {
                _personRemove = it
            }
    }


private var _personRemove: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun PersonRemoveIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.PersonRemove.imageVector,
            contentDescription = null,
    )
}
