@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.PinFilled: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _pinFilled ?: ImageVector.Builder(
                    name = "PinFilled",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        pathFillType = PathFillType.EvenOdd,
                ) {
                    moveTo(19.561f, 10.901f)
                    curveTo(20.993f, 10.45f, 21.436f, 8.641f, 20.375f, 7.579f)
                    lineTo(16.382f, 3.5869999999999997f)
                    curveTo(15.324000000000002f, 2.529f, 13.522000000000002f, 2.9639999999999995f, 13.064000000000002f, 4.388f)
                    lineTo(12.502000000000002f, 6.136f)
                    arcTo(2.0f, 2.0f, 17.834483397919865f, isMoreThanHalf = false, isPositiveArc = true, 12.012000000000002f, 6.938000000000001f)
                    lineTo(10.439000000000002f, 8.511000000000001f)
                    arcTo(2.0f, 2.0f, 45.031867453898954f, isMoreThanHalf = false, isPositiveArc = true, 9.025000000000002f, 9.096f)
                    lineTo(5.251f, 9.096f)
                    arcTo(2.0f, 2.0f, 270.00897435298566f, isMoreThanHalf = false, isPositiveArc = false, 3.7570000000000006f, 9.766f)
                    lineTo(3.6580000000000004f, 9.878f)
                    arcTo(1.0f, 1.0f, 221.66730197036287f, isMoreThanHalf = false, isPositiveArc = false, 3.6980000000000004f, 11.25f)
                    lineTo(7.506f, 15.057f)
                    lineTo(2.293f, 20.27f)
                    arcTo(1.0f, 1.0f, 225.02025241071948f, isMoreThanHalf = false, isPositiveArc = false, 3.707f, 21.685f)
                    lineTo(8.92f, 16.471999999999998f)
                    lineTo(12.764f, 20.316999999999997f)
                    arcTo(1.0f, 1.0f, 134.982196821352f, isMoreThanHalf = false, isPositiveArc = false, 14.200999999999999f, 20.292999999999996f)
                    lineTo(14.312999999999999f, 20.172999999999995f)
                    arcTo(2.0f, 2.0f, 43.1136060629929f, isMoreThanHalf = false, isPositiveArc = false, 14.852999999999998f, 18.805999999999994f)
                    lineTo(14.852999999999998f, 14.924999999999994f)
                    arcTo(2.0f, 2.0f, 179.98358975825263f, isMoreThanHalf = false, isPositiveArc = true, 15.438999999999998f, 13.509999999999994f)
                    lineTo(17.006999999999998f, 11.942999999999994f)
                    arcTo(2.0f, 2.0f, 224.97622114787927f, isMoreThanHalf = false, isPositiveArc = true, 17.820999999999998f, 11.448999999999995f)
                    close()
                }
            }.build().also {
                _pinFilled = it
            }
    }


private var _pinFilled: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun PinFilledIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.PinFilled.imageVector,
            contentDescription = null,
    )
}
