@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.Refresh: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _refresh ?: ImageVector.Builder(
                    name = "Refresh",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                        pathFillType = PathFillType.EvenOdd,
                ) {
                    moveTo(21.0f, 12.0f)
                    curveTo(20.448f, 12.0f, 20.007f, 12.45f, 19.938f, 12.998f)
                    curveTo(19.445f, 16.94f, 16.073f, 20.0f, 12.0f, 20.0f)
                    curveTo(7.589f, 20.0f, 4.0f, 16.411f, 4.0f, 12.0f)
                    curveTo(4.0f, 7.588999999999999f, 7.589f, 4.0f, 12.0f, 4.0f)
                    curveTo(14.117f, 4.0f, 16.107f, 4.819f, 17.613f, 6.303f)
                    lineTo(15.52f, 8.396f)
                    arcTo(0.5f, 0.5f, 225.07242377268008f, isMoreThanHalf = false, isPositiveArc = false, 15.873f, 9.25f)
                    lineTo(21.5f, 9.25f)
                    arcTo(0.5f, 0.5f, 90.0f, isMoreThanHalf = false, isPositiveArc = false, 22.0f, 8.75f)
                    lineTo(22.0f, 3.123f)
                    arcTo(0.5f, 0.5f, 359.9878298026262f, isMoreThanHalf = false, isPositiveArc = false, 21.146f, 2.7700000000000005f)
                    lineTo(19.027f, 4.889000000000001f)
                    arcTo(9.93f, 9.93f, 314.8414895123731f, isMoreThanHalf = false, isPositiveArc = false, 12.0f, 2.0f)
                    curveTo(6.486f, 2.0f, 2.0f, 6.486f, 2.0f, 12.0f)
                    curveTo(2.0f, 17.514f, 6.486f, 22.0f, 12.0f, 22.0f)
                    curveTo(17.177f, 22.0f, 21.448f, 18.046f, 21.95f, 12.999f)
                    curveTo(22.005f, 12.449f, 21.552f, 12.0f, 21.0f, 12.0f)
                }
            }.build().also {
                _refresh = it
            }
    }


private var _refresh: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun RefreshIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.Refresh.imageVector,
            contentDescription = null,
    )
}
