@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.SecurityPerson: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _securityPerson ?: ImageVector.Builder(
                    name = "SecurityPerson",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                ) {
                    moveTo(12.0007f, 11.5f)
                    curveTo(13.1046f, 11.5f, 14.0f, 10.6043f, 14.0f, 9.5f)
                    curveTo(14.0f, 8.3957f, 13.1046f, 7.5f, 12.0007f, 7.5f)
                    curveTo(10.8954f, 7.5f, 10.0f, 8.3957f, 10.0f, 9.5f)
                    curveTo(10.0f, 10.6043f, 10.8954f, 11.5f, 12.0007f, 11.5f)
                    close()
                    moveTo(8.00049f, 15.7388f)
                    curveTo(7.99135f, 15.8802f, 8.11135f, 16.0f, 8.25421f, 16.0f)
                    lineTo(15.7458f, 16.0f)
                    curveTo(15.8887f, 16.0f, 16.0087f, 15.8802f, 15.9995f, 15.7388f)
                    curveTo(15.8646f, 13.6504f, 14.1252f, 12.0f, 12.0006f, 12.0f)
                    curveTo(9.87481f, 12.0f, 8.13535f, 13.6504f, 8.00049f, 15.7388f)
                    close()
                }

                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                ) {
                    moveTo(21.0f, 5.30701f)
                    lineTo(12.0f, 1.93201f)
                    lineTo(3.0f, 5.30701f)
                    lineTo(3.0f, 10.0f)
                    curveTo(3.0f, 14.6688f, 5.63784f, 18.937f, 9.81378f, 21.0249f)
                    lineTo(12.0f, 22.118f)
                    lineTo(14.1862f, 21.0249f)
                    curveTo(18.3622f, 18.937f, 21.0f, 14.6688f, 21.0f, 10.0f)
                    lineTo(21.0f, 5.30701f)
                    close()
                    moveTo(5.0f, 10.0f)
                    lineTo(5.0f, 6.69301f)
                    lineTo(12.0f, 4.06801f)
                    lineTo(19.0f, 6.69301f)
                    lineTo(19.0f, 10.0f)
                    curveTo(19.0f, 13.9113f, 16.7902f, 17.4869f, 13.2918f, 19.2361f)
                    lineTo(12.0f, 19.882f)
                    lineTo(10.7082f, 19.2361f)
                    curveTo(7.20984f, 17.4869f, 5.0f, 13.9113f, 5.0f, 10.0f)
                    close()
                }
            }.build().also {
                _securityPerson = it
            }
    }


private var _securityPerson: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun SecurityPersonIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.SecurityPerson.imageVector,
            contentDescription = null,
    )
}
