@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.Settings: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _settings ?: ImageVector.Builder(
                    name = "Settings",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                ) {
                    moveTo(7.00018f, 12.0001f)
                    curveTo(7.00018f, 9.23926f, 9.23852f, 7.00009f, 12.0002f, 7.00009f)
                    curveTo(14.761f, 7.00009f, 17.0002f, 9.23926f, 17.0002f, 12.0001f)
                    curveTo(17.0002f, 14.7609f, 14.761f, 17.0001f, 12.0002f, 17.0001f)
                    curveTo(9.23852f, 17.0001f, 7.00018f, 14.7609f, 7.00018f, 12.0001f)
                    close()
                    moveTo(22.0002f, 13.5001f)
                    lineTo(22.0002f, 10.5001f)
                    lineTo(19.7702f, 10.1281f)
                    curveTo(19.5712f, 9.30609f, 19.2472f, 8.53409f, 18.8152f, 7.83209f)
                    lineTo(20.1312f, 5.98909f)
                    lineTo(18.0102f, 3.86809f)
                    lineTo(16.1672f, 5.18509f)
                    curveTo(15.4652f, 4.75309f, 14.6942f, 4.42909f, 13.8722f, 4.23009f)
                    lineTo(13.5002f, 2.00009f)
                    lineTo(10.5002f, 2.00009f)
                    lineTo(10.1282f, 4.23009f)
                    curveTo(9.30618f, 4.42909f, 8.53418f, 4.75309f, 7.83218f, 5.18509f)
                    lineTo(5.98918f, 3.86809f)
                    lineTo(3.86818f, 5.98909f)
                    lineTo(5.18418f, 7.83209f)
                    curveTo(4.75318f, 8.53409f, 4.42818f, 9.30609f, 4.23018f, 10.1281f)
                    lineTo(2.00018f, 10.5001f)
                    lineTo(2.00018f, 13.5001f)
                    lineTo(4.23018f, 13.8721f)
                    curveTo(4.42818f, 14.6941f, 4.75318f, 15.4661f, 5.18418f, 16.1681f)
                    lineTo(3.86818f, 18.0111f)
                    lineTo(5.98918f, 20.1321f)
                    lineTo(7.83218f, 18.8151f)
                    curveTo(8.53418f, 19.2461f, 9.30618f, 19.5711f, 10.1282f, 19.7701f)
                    lineTo(10.5002f, 22.0001f)
                    lineTo(13.5002f, 22.0001f)
                    lineTo(13.8722f, 19.7701f)
                    curveTo(14.6942f, 19.5711f, 15.4652f, 19.2461f, 16.1672f, 18.8151f)
                    lineTo(18.0102f, 20.1321f)
                    lineTo(20.1312f, 18.0111f)
                    lineTo(18.8152f, 16.1681f)
                    curveTo(19.2472f, 15.4661f, 19.5712f, 14.6941f, 19.7702f, 13.8721f)
                    lineTo(22.0002f, 13.5001f)
                    close()
                }
            }.build().also {
                _settings = it
            }
    }


private var _settings: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun SettingsIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.Settings.imageVector,
            contentDescription = null,
    )
}
