@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon

val BezierIcon.Shipping: ImageVector
    get() {
        return io.channel.bezier.icon._shipping ?: ImageVector.Builder(
                name = "Shipping",
                defaultWidth = 24.dp,
                defaultHeight = 24.dp,
                viewportWidth = 24f,
                viewportHeight = 24f,
        ).apply {
            path(
                    fill = SolidColor(Color(0xFF313234)),
                    strokeLineWidth = 1f,
            ) {
                moveTo(6.7023f, 7.0f)
                lineTo(11.0f, 7.0f)
                curveTo(11.5523f, 7.0f, 12.0f, 7.4477f, 12.0f, 8.0f)
                curveTo(12.0f, 8.5523f, 11.5523f, 9.0f, 11.0f, 9.0f)
                lineTo(3.0f, 9.0f)
                curveTo(2.4477f, 9.0f, 2.0f, 8.5523f, 2.0f, 8.0f)
                curveTo(2.0f, 7.4477f, 2.4477f, 7.0f, 3.0f, 7.0f)
                lineTo(4.632f, 7.0f)
                curveTo(5.1017f, 4.6901f, 7.1388f, 3.0f, 9.5311f, 3.0f)
                lineTo(17.4689f, 3.0f)
                curveTo(20.4764f, 3.0f, 22.8033f, 5.6359f, 22.4303f, 8.6202f)
                lineTo(21.4303f, 16.6202f)
                curveTo(21.1175f, 19.1223f, 18.9905f, 21.0f, 16.4689f, 21.0f)
                lineTo(8.5311f, 21.0f)
                curveTo(6.0847f, 21.0f, 4.0899f, 19.2569f, 3.6304f, 17.0f)
                lineTo(2.0f, 17.0f)
                curveTo(1.4477f, 17.0f, 1.0f, 16.5523f, 1.0f, 16.0f)
                curveTo(1.0f, 15.4477f, 1.4477f, 15.0f, 2.0f, 15.0f)
                lineTo(6.0f, 15.0f)
                curveTo(6.5523f, 15.0f, 7.0f, 15.4477f, 7.0f, 16.0f)
                curveTo(7.0f, 16.5523f, 6.5523f, 17.0f, 6.0f, 17.0f)
                lineTo(5.7011f, 17.0f)
                curveTo(6.1103f, 18.1542f, 7.2122f, 19.0f, 8.5311f, 19.0f)
                lineTo(16.4689f, 19.0f)
                curveTo(17.9818f, 19.0f, 19.258f, 17.8734f, 19.4457f, 16.3721f)
                lineTo(20.4457f, 8.3721f)
                curveTo(20.6695f, 6.5815f, 19.2734f, 5.0f, 17.4689f, 5.0f)
                lineTo(9.5311f, 5.0f)
                curveTo(8.2378f, 5.0f, 7.1175f, 5.8232f, 6.7023f, 7.0f)
                close()
                moveTo(8.0f, 13.0f)
                lineTo(2.5f, 13.0f)
                curveTo(1.9477f, 13.0f, 1.5f, 12.5523f, 1.5f, 12.0f)
                curveTo(1.5f, 11.4477f, 1.9477f, 11.0f, 2.5f, 11.0f)
                lineTo(8.0f, 11.0f)
                curveTo(8.5523f, 11.0f, 9.0f, 11.4477f, 9.0f, 12.0f)
                curveTo(9.0f, 12.5523f, 8.5523f, 13.0f, 8.0f, 13.0f)
                close()
            }
        }.build().also {
            io.channel.bezier.icon._shipping = it
        }
    }

private var _shipping: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun ShippingIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcon.Shipping,
            contentDescription = null,
    )
}
