@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.Tool: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _tool ?: ImageVector.Builder(
                    name = "Tool",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                ) {
                    moveTo(6.664f, 6.664f)
                    arcTo(1.0f, 1.0f, 45.008099291896166f, isMoreThanHalf = false, isPositiveArc = true, 5.253f, 6.667f)
                    lineTo(3.836f, 5.25f)
                    arcTo(2.0f, 2.0f, 224.99134833716198f, isMoreThanHalf = false, isPositiveArc = false, 3.836f, 8.078f)
                    lineTo(4.779f, 9.020999999999999f)
                    arcTo(2.67f, 2.67f, 134.9626135777236f, isMoreThanHalf = false, isPositiveArc = false, 7.971f, 9.460999999999999f)
                    lineTo(10.356f, 12.143999999999998f)
                    lineTo(8.421f, 14.077999999999998f)
                    lineTo(9.835999999999999f, 15.492999999999999f)
                    lineTo(11.686999999999998f, 13.640999999999998f)
                    lineTo(17.357f, 20.017999999999997f)
                    arcTo(1.886f, 1.886f, 138.5806718340205f, isMoreThanHalf = true, isPositiveArc = false, 20.019f, 17.355999999999998f)
                    lineTo(13.640999999999998f, 11.686999999999998f)
                    lineTo(17.2f, 8.13f)
                    lineTo(17.907f, 8.837000000000002f)
                    lineTo(20.735f, 4.594000000000001f)
                    lineTo(19.320999999999998f, 3.1800000000000015f)
                    lineTo(15.077999999999998f, 6.008000000000001f)
                    lineTo(15.784999999999998f, 6.715000000000001f)
                    lineTo(12.143999999999998f, 10.357000000000001f)
                    lineTo(9.46f, 7.971f)
                    arcTo(2.67f, 2.67f, 29.26570553527607f, isMoreThanHalf = false, isPositiveArc = false, 9.020000000000001f, 4.779f)
                    lineTo(8.077000000000002f, 3.836f)
                    arcTo(2.0f, 2.0f, 314.991348337162f, isMoreThanHalf = false, isPositiveArc = false, 5.249000000000002f, 3.836f)
                    lineTo(7.6060000000000025f, 6.193f)
                    lineTo(6.666000000000002f, 5.253f)
                    arcTo(1.0f, 1.0f, 315.2517379588461f, isMoreThanHalf = false, isPositiveArc = true, 6.663000000000002f, 6.664f)
                    moveTo(10.543f, 16.2f)
                    lineTo(6.3f, 20.442f)
                    arcTo(2.0f, 2.0f, 44.00425538642053f, isMoreThanHalf = true, isPositiveArc = true, 3.472f, 17.614f)
                    lineTo(7.714f, 13.371f)
                    close()
                }
            }.build().also {
                _tool = it
            }
    }


private var _tool: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun ToolIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.Tool.imageVector,
            contentDescription = null,
    )
}
