@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.TriangleRightCircle: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _triangleRightCircle ?: ImageVector.Builder(
                    name = "TriangleRightCircle",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                ) {
                    moveTo(4.00018f, 12.0001f)
                    curveTo(4.00018f, 16.4111f, 7.58918f, 20.0001f, 12.0002f, 20.0001f)
                    curveTo(16.4112f, 20.0001f, 20.0002f, 16.4111f, 20.0002f, 12.0001f)
                    curveTo(20.0002f, 7.58912f, 16.4112f, 4.00012f, 12.0002f, 4.00012f)
                    curveTo(7.58918f, 4.00012f, 4.00018f, 7.58912f, 4.00018f, 12.0001f)
                    close()
                    moveTo(2.00018f, 12.0001f)
                    curveTo(2.00018f, 6.47712f, 6.47718f, 2.00012f, 12.0002f, 2.00012f)
                    curveTo(17.5232f, 2.00012f, 22.0002f, 6.47712f, 22.0002f, 12.0001f)
                    curveTo(22.0002f, 17.5231f, 17.5232f, 22.0001f, 12.0002f, 22.0001f)
                    curveTo(6.47718f, 22.0001f, 2.00018f, 17.5231f, 2.00018f, 12.0001f)
                    close()
                    moveTo(9.95148f, 7.65104f)
                    curveTo(9.95148f, 7.39704f, 10.2485f, 7.25804f, 10.4435f, 7.42104f)
                    lineTo(15.6745f, 11.78f)
                    curveTo(15.8185f, 11.9f, 15.8185f, 12.122f, 15.6745f, 12.241f)
                    lineTo(10.4435f, 16.601f)
                    curveTo(10.2485f, 16.764f, 9.95148f, 16.625f, 9.95148f, 16.371f)
                    lineTo(9.95148f, 7.65104f)
                    close()
                }
            }.build().also {
                _triangleRightCircle = it
            }
    }


private var _triangleRightCircle: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun TriangleRightCircleIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.TriangleRightCircle.imageVector,
            contentDescription = null,
    )
}
