@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.VideocamOff: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _videocamOff ?: ImageVector.Builder(
                    name = "VideocamOff",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                ) {
                    moveTo(6.20711f, 1.79289f)
                    curveTo(5.81658f, 1.40237f, 5.18342f, 1.40237f, 4.79289f, 1.79289f)
                    curveTo(4.40237f, 2.18342f, 4.40237f, 2.81658f, 4.79289f, 3.20711f)
                    lineTo(19.8661f, 18.2803f)
                    curveTo(20.6536f, 19.0678f, 22.0f, 18.5101f, 22.0f, 17.3964f)
                    lineTo(22.0f, 6.60355f)
                    curveTo(22.0f, 5.48993f, 20.6536f, 4.93221f, 19.8661f, 5.71967f)
                    lineTo(16.9983f, 8.58749f)
                    curveTo(16.9955f, 8.29738f, 16.9883f, 8.03593f, 16.9694f, 7.80497f)
                    curveTo(16.9371f, 7.40963f, 16.8658f, 7.01641f, 16.673f, 6.63803f)
                    curveTo(16.3854f, 6.07354f, 15.9265f, 5.6146f, 15.362f, 5.32698f)
                    curveTo(14.9836f, 5.13419f, 14.5904f, 5.06287f, 14.195f, 5.03057f)
                    curveTo(13.8205f, 4.99997f, 13.3657f, 4.99998f, 12.8386f, 5.0f)
                    lineTo(9.41422f, 5.0f)
                    lineTo(6.20711f, 1.79289f)
                    close()
                    moveTo(11.4142f, 7.0f)
                    lineTo(15.0f, 10.5858f)
                    lineTo(15.0f, 9.2f)
                    curveTo(15.0f, 8.62345f, 14.9992f, 8.25117f, 14.9761f, 7.96784f)
                    curveTo(14.9539f, 7.69617f, 14.9162f, 7.59546f, 14.891f, 7.54601f)
                    curveTo(14.7951f, 7.35785f, 14.6422f, 7.20487f, 14.454f, 7.109f)
                    curveTo(14.4046f, 7.0838f, 14.3038f, 7.04612f, 14.0322f, 7.02393f)
                    curveTo(13.7488f, 7.00078f, 13.3766f, 7.0f, 12.8f, 7.0f)
                    lineTo(11.4142f, 7.0f)
                    close()
                    moveTo(17.0f, 12.5858f)
                    lineTo(20.0f, 15.5858f)
                    lineTo(20.0f, 8.41421f)
                    lineTo(17.0f, 11.4142f)
                    lineTo(17.0f, 12.5858f)
                    close()
                }

                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                ) {
                    moveTo(4.80498f, 5.03057f)
                    curveTo(4.92462f, 5.0208f, 5.05245f, 5.01414f, 5.18821f, 5.00962f)
                    lineTo(7.17859f, 7.0f)
                    lineTo(6.2f, 7.0f)
                    curveTo(5.62345f, 7.0f, 5.25118f, 7.00078f, 4.96784f, 7.02393f)
                    curveTo(4.69618f, 7.04612f, 4.59546f, 7.0838f, 4.54601f, 7.109f)
                    curveTo(4.35785f, 7.20487f, 4.20487f, 7.35785f, 4.109f, 7.54601f)
                    curveTo(4.0838f, 7.59546f, 4.04613f, 7.69617f, 4.02393f, 7.96784f)
                    curveTo(4.00078f, 8.25117f, 4.0f, 8.62345f, 4.0f, 9.2f)
                    lineTo(4.0f, 14.8f)
                    curveTo(4.0f, 15.3766f, 4.00078f, 15.7488f, 4.02393f, 16.0322f)
                    curveTo(4.04613f, 16.3038f, 4.0838f, 16.4045f, 4.109f, 16.454f)
                    curveTo(4.20487f, 16.6422f, 4.35785f, 16.7951f, 4.54601f, 16.891f)
                    curveTo(4.59546f, 16.9162f, 4.69618f, 16.9539f, 4.96784f, 16.9761f)
                    curveTo(5.25118f, 16.9992f, 5.62345f, 17.0f, 6.2f, 17.0f)
                    lineTo(12.8f, 17.0f)
                    curveTo(13.3766f, 17.0f, 13.7488f, 16.9992f, 14.0322f, 16.9761f)
                    curveTo(14.3038f, 16.9539f, 14.4046f, 16.9162f, 14.454f, 16.891f)
                    curveTo(14.6422f, 16.7951f, 14.7951f, 16.6422f, 14.891f, 16.454f)
                    curveTo(14.9162f, 16.4045f, 14.9539f, 16.3038f, 14.9761f, 16.0322f)
                    curveTo(14.9989f, 15.7524f, 15.0f, 15.3858f, 15.0f, 14.8214f)
                    lineTo(16.8964f, 16.7178f)
                    curveTo(16.8502f, 16.9357f, 16.7805f, 17.1511f, 16.673f, 17.362f)
                    curveTo(16.3854f, 17.9265f, 15.9265f, 18.3854f, 15.362f, 18.673f)
                    curveTo(14.9836f, 18.8658f, 14.5904f, 18.9371f, 14.195f, 18.9694f)
                    curveTo(13.8205f, 19.0f, 13.3657f, 19.0f, 12.8386f, 19.0f)
                    lineTo(6.16148f, 19.0f)
                    curveTo(5.63435f, 19.0f, 5.17954f, 19.0f, 4.80498f, 18.9694f)
                    curveTo(4.40963f, 18.9371f, 4.01641f, 18.8658f, 3.63803f, 18.673f)
                    curveTo(3.07355f, 18.3854f, 2.6146f, 17.9265f, 2.32698f, 17.362f)
                    curveTo(2.13419f, 16.9836f, 2.06287f, 16.5904f, 2.03057f, 16.195f)
                    curveTo(1.99997f, 15.8205f, 1.99998f, 15.3657f, 2.0f, 14.8386f)
                    lineTo(2.0f, 9.16146f)
                    curveTo(1.99998f, 8.63434f, 1.99997f, 8.17953f, 2.03057f, 7.80497f)
                    curveTo(2.06287f, 7.40963f, 2.13419f, 7.01641f, 2.32698f, 6.63803f)
                    curveTo(2.6146f, 6.07354f, 3.07355f, 5.6146f, 3.63803f, 5.32698f)
                    curveTo(4.01641f, 5.13419f, 4.40963f, 5.06287f, 4.80498f, 5.03057f)
                    close()
                }
            }.build().also {
                _videocamOff = it
            }
    }


private var _videocamOff: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun VideocamOffIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.VideocamOff.imageVector,
            contentDescription = null,
    )
}
