@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.VideocamFilled: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _videocamFilled ?: ImageVector.Builder(
                    name = "VideocamFilled",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                        pathFillType = PathFillType.EvenOdd,
                ) {
                    moveTo(13.998f, 6.0f)
                    lineTo(4.002f, 6.0f)
                    arcTo(2.0f, 2.0f, 270.0f, isMoreThanHalf = false, isPositiveArc = false, 2.002f, 8.0f)
                    lineTo(2.002f, 16.0f)
                    arcTo(2.0f, 2.0f, 180.0f, isMoreThanHalf = false, isPositiveArc = false, 4.002f, 18.0f)
                    lineTo(13.998000000000001f, 18.0f)
                    arcTo(2.0f, 2.0f, 90.0f, isMoreThanHalf = false, isPositiveArc = false, 15.998000000000001f, 16.0f)
                    lineTo(15.998000000000001f, 8.0f)
                    arcTo(2.0f, 2.0f, 0.0f, isMoreThanHalf = false, isPositiveArc = false, 13.998000000000001f, 6.0f)
                    moveTo(21.188000000000002f, 17.35f)
                    lineTo(17.188000000000002f, 14.150000000000002f)
                    arcTo(0.5f, 0.5f, 128.75562134106767f, isMoreThanHalf = false, isPositiveArc = true, 17.001f, 13.760000000000002f)
                    lineTo(17.001f, 10.240000000000002f)
                    arcTo(0.5f, 0.5f, 179.98986262433894f, isMoreThanHalf = false, isPositiveArc = true, 17.188000000000002f, 9.850000000000001f)
                    lineTo(21.188000000000002f, 6.650000000000001f)
                    arcTo(0.5f, 0.5f, 231.39109801289013f, isMoreThanHalf = false, isPositiveArc = true, 22.000000000000004f, 7.040000000000001f)
                    lineTo(22.000000000000004f, 16.96f)
                    arcTo(0.5f, 0.5f, 0.08156237144868975f, isMoreThanHalf = false, isPositiveArc = true, 21.188000000000002f, 17.35f)
                }
            }.build().also {
                _videocamFilled = it
            }
    }


private var _videocamFilled: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun VideocamFilledIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.VideocamFilled.imageVector,
            contentDescription = null,
    )
}
