@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.annotation.DrawableRes
import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons
import io.channel.bezier.compose.R

val BezierIcons.VolumeUpFilled: BezierIcon
    get() = object : BezierIcon {
        @DrawableRes
        override val resourceId: Int = R.drawable.icon_volume_up_filled
        override val imageVector: ImageVector
            get() = _volumeUpFilled ?: ImageVector.Builder(
                    name = "VolumeUpFilled",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        pathFillType = PathFillType.EvenOdd,
                ) {
                    moveTo(13.014f, 2.0f)
                    lineTo(14.014f, 2.0f)
                    arcTo(1.0f, 1.0f, 270.0f, isMoreThanHalf = false, isPositiveArc = true, 15.014f, 3.0f)
                    lineTo(15.014f, 21.0f)
                    arcTo(1.0f, 1.0f, 0.0f, isMoreThanHalf = false, isPositiveArc = true, 14.014f, 22.0f)
                    lineTo(13.014f, 22.0f)
                    arcTo(1.0f, 1.0f, 90.06947490702143f, isMoreThanHalf = false, isPositiveArc = true, 12.306999999999999f, 21.706f)
                    lineTo(7.6f, 17.0f)
                    lineTo(3.014f, 17.0f)
                    arcTo(1.0f, 1.0f, 90.0f, isMoreThanHalf = false, isPositiveArc = true, 2.014f, 16.0f)
                    lineTo(2.014f, 8.0f)
                    arcTo(1.0f, 1.0f, 180.0f, isMoreThanHalf = false, isPositiveArc = true, 3.014f, 7.0f)
                    lineTo(7.6f, 7.0f)
                    lineTo(12.306999999999999f, 2.293f)
                    arcTo(1.0f, 1.0f, 224.9913464895163f, isMoreThanHalf = false, isPositiveArc = true, 13.014f, 2.0f)
                    moveTo(19.407f, 6.414f)
                    curveTo(19.797f, 6.024f, 20.436f, 6.02f, 20.78f, 6.452f)
                    arcTo(8.92f, 8.92f, 321.5437375403024f, isMoreThanHalf = false, isPositiveArc = true, 20.78f, 17.547f)
                    curveTo(20.436f, 17.979f, 19.797f, 17.976f, 19.407f, 17.585f)
                    curveTo(19.017f, 17.195f, 19.024f, 16.565f, 19.354f, 16.123f)
                    arcTo(6.92f, 6.92f, 36.57549798267761f, isMoreThanHalf = false, isPositiveArc = false, 19.354f, 7.876000000000001f)
                    curveTo(19.024f, 7.434000000000001f, 19.016f, 6.804000000000001f, 19.407f, 6.4140000000000015f)
                    moveTo(16.99f, 8.83f)
                    curveTo(17.38f, 8.44f, 18.023999999999997f, 8.436f, 18.337f, 8.89f)
                    arcTo(5.5f, 5.5f, 325.5724533224715f, isMoreThanHalf = false, isPositiveArc = true, 18.337f, 15.109000000000002f)
                    curveTo(18.023f, 15.564000000000002f, 17.381f, 15.559000000000001f, 16.991f, 15.169000000000002f)
                    curveTo(16.601f, 14.779000000000003f, 16.617f, 14.149000000000003f, 16.881f, 13.664000000000001f)
                    arcTo(3.5f, 3.5f, 28.39656220578764f, isMoreThanHalf = false, isPositiveArc = false, 16.881f, 10.335f)
                    curveTo(16.617f, 9.850000000000001f, 16.6f, 9.221f, 16.991f, 8.830000000000002f)
                }
            }.build().also {
                _volumeUpFilled = it
            }
    }


private var _volumeUpFilled: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun VolumeUpFilledIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.VolumeUpFilled.imageVector,
            contentDescription = null,
    )
}
