@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.BezierIcon
import io.channel.bezier.BezierIcons

val BezierIcons.WeatherCloudy: BezierIcon
    get() = object : BezierIcon {
        override val imageVector: ImageVector
            get() = _weatherCloudy ?: ImageVector.Builder(
                    name = "WeatherCloudy",
                    defaultWidth = 24.dp,
                    defaultHeight = 24.dp,
                    viewportWidth = 24f,
                    viewportHeight = 24f,
            ).apply {
                path(
                        fill = SolidColor(Color(0xFF313234)),
                        strokeLineWidth = 1f,
                        strokeAlpha = 1.0f,
                ) {
                    moveTo(11.0f, 4.953f)
                    lineTo(9.0f, 4.953f)
                    lineTo(9.0f, 2.453f)
                    lineTo(11.0f, 2.453f)
                    lineTo(11.0f, 4.953f)
                    close()
                    moveTo(6.46452f, 6.00297f)
                    lineTo(4.70752f, 4.24597f)
                    lineTo(3.29352f, 5.65997f)
                    lineTo(5.05052f, 7.41697f)
                    lineTo(6.46452f, 6.00297f)
                    close()
                    moveTo(1.5f, 11.953f)
                    lineTo(4.0f, 11.953f)
                    lineTo(4.0f, 9.953f)
                    lineTo(1.5f, 9.953f)
                    lineTo(1.5f, 11.953f)
                    close()
                    moveTo(16.7072f, 5.66022f)
                    lineTo(15.2932f, 4.24622f)
                    lineTo(13.5362f, 6.00322f)
                    lineTo(14.9502f, 7.41722f)
                    lineTo(16.7072f, 5.66022f)
                    close()
                    moveTo(8.21569f, 19.0001f)
                    lineTo(16.9367f, 19.0001f)
                    curveTo(18.6257f, 19.0001f, 19.9997f, 17.6251f, 19.9997f, 15.9361f)
                    curveTo(19.9997f, 14.2461f, 18.6257f, 12.8721f, 16.9367f, 12.8721f)
                    lineTo(15.8637f, 12.8721f)
                    lineTo(15.5737f, 12.3771f)
                    curveTo(15.0347f, 11.4561f, 14.0867f, 10.9061f, 13.0397f, 10.9061f)
                    curveTo(11.5917f, 10.9061f, 10.3437f, 11.9931f, 10.1357f, 13.4351f)
                    lineTo(10.0127f, 14.2921f)
                    lineTo(8.21569f, 14.2921f)
                    curveTo(6.99369f, 14.2921f, 5.99969f, 15.2861f, 5.99969f, 16.5081f)
                    lineTo(5.99969f, 16.7841f)
                    curveTo(5.99969f, 18.0061f, 6.99369f, 19.0001f, 8.21569f, 19.0001f)
                    close()
                    moveTo(9.99969f, 8.45312f)
                    curveTo(8.62169f, 8.45312f, 7.49969f, 9.57413f, 7.49969f, 10.9531f)
                    curveTo(7.49969f, 11.4441f, 7.64469f, 11.9151f, 7.91369f, 12.3221f)
                    curveTo(7.95563f, 12.3192f, 7.99655f, 12.3137f, 8.03743f, 12.3081f)
                    curveTo(8.09598f, 12.3001f, 8.15445f, 12.2921f, 8.21569f, 12.2921f)
                    lineTo(8.35969f, 12.2921f)
                    curveTo(8.8777f, 10.7461f, 10.1387f, 9.56213f, 11.6827f, 9.11112f)
                    curveTo(11.2257f, 8.69513f, 10.6297f, 8.45312f, 9.99969f, 8.45312f)
                    close()
                    moveTo(14.1507f, 9.03713f)
                    curveTo(15.2637f, 9.30013f, 16.2667f, 9.94613f, 16.9687f, 10.8721f)
                    curveTo(19.7467f, 10.8901f, 21.9997f, 13.1541f, 21.9997f, 15.9361f)
                    curveTo(21.9997f, 18.7291f, 19.7287f, 21.0001f, 16.9367f, 21.0001f)
                    lineTo(8.21569f, 21.0001f)
                    curveTo(5.8917f, 21.0001f, 3.99969f, 19.1081f, 3.99969f, 16.7841f)
                    lineTo(3.99969f, 16.5081f)
                    curveTo(3.99969f, 15.0111f, 4.79069f, 13.7011f, 5.9697f, 12.9531f)
                    curveTo(5.66269f, 12.3351f, 5.49969f, 11.6541f, 5.49969f, 10.9531f)
                    curveTo(5.49969f, 8.47213f, 7.51869f, 6.45312f, 9.99969f, 6.45312f)
                    curveTo(11.4707f, 6.45312f, 12.8507f, 7.17412f, 13.6927f, 8.38112f)
                    lineTo(14.1507f, 9.03713f)
                    close()
                }
            }.build().also {
                _weatherCloudy = it
            }
    }


private var _weatherCloudy: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun WeatherCloudyIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcons.WeatherCloudy.imageVector,
            contentDescription = null,
    )
}
