@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.compose.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.*
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.compose.BezierIcon

val BezierIcon.ArrowRightDownSmall: ImageVector
    get() {
        return _arrowRightDownSmall ?: ImageVector.Builder(
                name = "ArrowRightDownSmall",
                defaultWidth = 24.dp,
                defaultHeight = 24.dp,
                viewportWidth = 24f,
                viewportHeight = 24f,
        ).apply {
            path(
                    fill = SolidColor(Color(0xFF313234)),
                    strokeLineWidth = 1f,
            ) {
                moveTo(7.0503f, 7.0503f)
                curveTo(6.6597f, 7.4408f, 6.6597f, 8.074f, 7.0503f, 8.4645f)
                lineTo(13.8285f, 15.2427f)
                lineTo(8.4645f, 15.2427f)
                curveTo(7.9122f, 15.2427f, 7.4645f, 15.6904f, 7.4645f, 16.2427f)
                curveTo(7.4645f, 16.795f, 7.9122f, 17.2427f, 8.4645f, 17.2427f)
                lineTo(16.2427f, 17.2427f)
                curveTo(16.795f, 17.2427f, 17.2427f, 16.795f, 17.2427f, 16.2427f)
                lineTo(17.2427f, 8.4645f)
                curveTo(17.2427f, 7.9122f, 16.795f, 7.4645f, 16.2427f, 7.4645f)
                curveTo(15.6904f, 7.4645f, 15.2427f, 7.9122f, 15.2427f, 8.4645f)
                lineTo(15.2427f, 13.8285f)
                lineTo(8.4645f, 7.0503f)
                curveTo(8.074f, 6.6597f, 7.4408f, 6.6597f, 7.0503f, 7.0503f)
                close()
            }
        }.build().also {
            _arrowRightDownSmall = it
        }
    }

private var _arrowRightDownSmall: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun ArrowRightDownSmallIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcon.ArrowRightDownSmall,
            contentDescription = null,
    )
}
