@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.compose.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.compose.BezierIcon

val BezierIcon.ChannelsList: ImageVector
    get() {
        return _channelsList ?: ImageVector.Builder(
                name = "ChannelsList",
                defaultWidth = 24.dp,
                defaultHeight = 24.dp,
                viewportWidth = 24f,
                viewportHeight = 24f,
        ).apply {
            path(
                    fill = SolidColor(Color(0xFF313234)),
                    strokeLineWidth = 1f,
                    pathFillType = PathFillType.EvenOdd,
            ) {
                moveTo(7.0002f, 7.5001f)
                lineTo(3.5002f, 7.5001f)
                curveTo(3.2242f, 7.5001f, 3.0002f, 7.2761f, 3.0002f, 7.0001f)
                lineTo(3.0002f, 3.5001f)
                curveTo(3.0002f, 3.2241f, 3.2242f, 3.0001f, 3.5002f, 3.0001f)
                lineTo(7.0002f, 3.0001f)
                curveTo(7.2762f, 3.0001f, 7.5002f, 3.2241f, 7.5002f, 3.5001f)
                lineTo(7.5002f, 7.0001f)
                curveTo(7.5002f, 7.2761f, 7.2762f, 7.5001f, 7.0002f, 7.5001f)
                close()
                moveTo(13.7502f, 7.5001f)
                lineTo(10.2502f, 7.5001f)
                curveTo(9.9742f, 7.5001f, 9.7502f, 7.2761f, 9.7502f, 7.0001f)
                lineTo(9.7502f, 3.5001f)
                curveTo(9.7502f, 3.2241f, 9.9742f, 3.0001f, 10.2502f, 3.0001f)
                lineTo(13.7502f, 3.0001f)
                curveTo(14.0262f, 3.0001f, 14.2502f, 3.2241f, 14.2502f, 3.5001f)
                lineTo(14.2502f, 7.0001f)
                curveTo(14.2502f, 7.2761f, 14.0262f, 7.5001f, 13.7502f, 7.5001f)
                close()
                moveTo(17.0002f, 7.5001f)
                lineTo(20.5002f, 7.5001f)
                curveTo(20.7762f, 7.5001f, 21.0002f, 7.2761f, 21.0002f, 7.0001f)
                lineTo(21.0002f, 3.5001f)
                curveTo(21.0002f, 3.2241f, 20.7762f, 3.0001f, 20.5002f, 3.0001f)
                lineTo(17.0002f, 3.0001f)
                curveTo(16.7242f, 3.0001f, 16.5002f, 3.2241f, 16.5002f, 3.5001f)
                lineTo(16.5002f, 7.0001f)
                curveTo(16.5002f, 7.2761f, 16.7242f, 7.5001f, 17.0002f, 7.5001f)
                close()
                moveTo(7.0002f, 14.2501f)
                lineTo(3.5002f, 14.2501f)
                curveTo(3.2242f, 14.2501f, 3.0002f, 14.0261f, 3.0002f, 13.7501f)
                lineTo(3.0002f, 10.2501f)
                curveTo(3.0002f, 9.9741f, 3.2242f, 9.7501f, 3.5002f, 9.7501f)
                lineTo(7.0002f, 9.7501f)
                curveTo(7.2762f, 9.7501f, 7.5002f, 9.9741f, 7.5002f, 10.2501f)
                lineTo(7.5002f, 13.7501f)
                curveTo(7.5002f, 14.0261f, 7.2762f, 14.2501f, 7.0002f, 14.2501f)
                close()
                moveTo(10.2502f, 14.2501f)
                lineTo(13.7502f, 14.2501f)
                curveTo(14.0262f, 14.2501f, 14.2502f, 14.0261f, 14.2502f, 13.7501f)
                lineTo(14.2502f, 10.2501f)
                curveTo(14.2502f, 9.9741f, 14.0262f, 9.7501f, 13.7502f, 9.7501f)
                lineTo(10.2502f, 9.7501f)
                curveTo(9.9742f, 9.7501f, 9.7502f, 9.9741f, 9.7502f, 10.2501f)
                lineTo(9.7502f, 13.7501f)
                curveTo(9.7502f, 14.0261f, 9.9742f, 14.2501f, 10.2502f, 14.2501f)
                close()
                moveTo(20.5002f, 14.2501f)
                lineTo(17.0002f, 14.2501f)
                curveTo(16.7242f, 14.2501f, 16.5002f, 14.0261f, 16.5002f, 13.7501f)
                lineTo(16.5002f, 10.2501f)
                curveTo(16.5002f, 9.9741f, 16.7242f, 9.7501f, 17.0002f, 9.7501f)
                lineTo(20.5002f, 9.7501f)
                curveTo(20.7762f, 9.7501f, 21.0002f, 9.9741f, 21.0002f, 10.2501f)
                lineTo(21.0002f, 13.7501f)
                curveTo(21.0002f, 14.0261f, 20.7762f, 14.2501f, 20.5002f, 14.2501f)
                close()
                moveTo(3.5002f, 21.0001f)
                lineTo(7.0002f, 21.0001f)
                curveTo(7.2762f, 21.0001f, 7.5002f, 20.7761f, 7.5002f, 20.5001f)
                lineTo(7.5002f, 17.0001f)
                curveTo(7.5002f, 16.7241f, 7.2762f, 16.5001f, 7.0002f, 16.5001f)
                lineTo(3.5002f, 16.5001f)
                curveTo(3.2242f, 16.5001f, 3.0002f, 16.7241f, 3.0002f, 17.0001f)
                lineTo(3.0002f, 20.5001f)
                curveTo(3.0002f, 20.7761f, 3.2242f, 21.0001f, 3.5002f, 21.0001f)
                close()
                moveTo(13.7502f, 21.0001f)
                lineTo(10.2502f, 21.0001f)
                curveTo(9.9742f, 21.0001f, 9.7502f, 20.7761f, 9.7502f, 20.5001f)
                lineTo(9.7502f, 17.0001f)
                curveTo(9.7502f, 16.7241f, 9.9742f, 16.5001f, 10.2502f, 16.5001f)
                lineTo(13.7502f, 16.5001f)
                curveTo(14.0262f, 16.5001f, 14.2502f, 16.7241f, 14.2502f, 17.0001f)
                lineTo(14.2502f, 20.5001f)
                curveTo(14.2502f, 20.7761f, 14.0262f, 21.0001f, 13.7502f, 21.0001f)
                close()
                moveTo(17.0002f, 21.0001f)
                lineTo(20.5002f, 21.0001f)
                curveTo(20.7762f, 21.0001f, 21.0002f, 20.7761f, 21.0002f, 20.5001f)
                lineTo(21.0002f, 17.0001f)
                curveTo(21.0002f, 16.7241f, 20.7762f, 16.5001f, 20.5002f, 16.5001f)
                lineTo(17.0002f, 16.5001f)
                curveTo(16.7242f, 16.5001f, 16.5002f, 16.7241f, 16.5002f, 17.0001f)
                lineTo(16.5002f, 20.5001f)
                curveTo(16.5002f, 20.7761f, 16.7242f, 21.0001f, 17.0002f, 21.0001f)
                close()
            }
        }.build().also {
            _channelsList = it
        }
    }

private var _channelsList: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun ChannelsListIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcon.ChannelsList,
            contentDescription = null,
    )
}
