@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.compose.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.compose.BezierIcon

val BezierIcon.Dropdown: ImageVector
    get() {
        return _dropdown ?: ImageVector.Builder(
                name = "Dropdown",
                defaultWidth = 24.dp,
                defaultHeight = 24.dp,
                viewportWidth = 24f,
                viewportHeight = 24f,
        ).apply {
            path(
                    fill = SolidColor(Color(0xFF313234)),
                    strokeLineWidth = 1f,
            ) {
                moveTo(16.2596f, 14.2593f)
                curveTo(16.0614f, 14.5536f, 15.6284f, 14.5536f, 15.4302f, 14.2593f)
                lineTo(13.0861f, 10.7793f)
                curveTo(12.8624f, 10.4472f, 13.1004f, 10.0f, 13.5008f, 10.0f)
                lineTo(18.1889f, 10.0f)
                curveTo(18.5894f, 10.0f, 18.8273f, 10.4472f, 18.6036f, 10.7793f)
                lineTo(16.2596f, 14.2593f)
                close()
            }

            path(
                    fill = SolidColor(Color(0xFF313234)),
                    strokeLineWidth = 1f,
                    pathFillType = PathFillType.EvenOdd,
            ) {
                moveTo(1.0f, 8.0f)
                curveTo(1.0f, 6.3432f, 2.3431f, 5.0f, 4.0f, 5.0f)
                lineTo(20.0f, 5.0f)
                curveTo(21.6569f, 5.0f, 23.0f, 6.3432f, 23.0f, 8.0f)
                lineTo(23.0f, 16.0f)
                curveTo(23.0f, 17.6569f, 21.6569f, 19.0f, 20.0f, 19.0f)
                lineTo(4.0f, 19.0f)
                curveTo(2.3431f, 19.0f, 1.0f, 17.6569f, 1.0f, 16.0f)
                lineTo(1.0f, 8.0f)
                close()
                moveTo(4.0f, 7.0f)
                lineTo(20.0f, 7.0f)
                curveTo(20.5523f, 7.0f, 21.0f, 7.4477f, 21.0f, 8.0f)
                lineTo(21.0f, 16.0f)
                curveTo(21.0f, 16.5523f, 20.5523f, 17.0f, 20.0f, 17.0f)
                lineTo(4.0f, 17.0f)
                curveTo(3.4477f, 17.0f, 3.0f, 16.5523f, 3.0f, 16.0f)
                lineTo(3.0f, 8.0f)
                curveTo(3.0f, 7.4477f, 3.4477f, 7.0f, 4.0f, 7.0f)
                close()
            }
        }.build().also {
            _dropdown = it
        }
    }

private var _dropdown: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun DropdownIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcon.Dropdown,
            contentDescription = null,
    )
}
