@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.compose.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.*
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.compose.BezierIcon

val BezierIcon.GooglePlay: ImageVector
    get() {
        return _googlePlay ?: ImageVector.Builder(
                name = "GooglePlay",
                defaultWidth = 24.dp,
                defaultHeight = 24.dp,
                viewportWidth = 24f,
                viewportHeight = 24f,
        ).apply {
            path(
                    fill = SolidColor(Color(0x66313234)),
                    strokeLineWidth = 1f,
                    strokeAlpha = 0.4f,
            ) {
                moveTo(13.0f, 12.0f)
                lineTo(5.0739f, 19.5024f)
                curveTo(5.3177f, 20.3632f, 6.1452f, 20.993f, 7.1278f, 20.993f)
                curveTo(7.5193f, 20.993f, 7.8888f, 20.895f, 8.2064f, 20.7131f)
                lineTo(8.2286f, 20.6991f)
                lineTo(17.0795f, 15.8632f)
                lineTo(13.0f, 12.0f)
                close()
            }

            path(
                    fill = SolidColor(Color(0x99313234)),
                    strokeLineWidth = 1f,
                    strokeAlpha = 0.6f,
            ) {
                moveTo(20.8992f, 10.2503f)
                lineTo(20.8918f, 10.2503f)
                lineTo(17.0721f, 8.1438f)
                lineTo(13.0f, 12.0f)
                lineTo(17.0869f, 15.8701f)
                lineTo(20.8918f, 13.7915f)
                curveTo(21.5567f, 13.4486f, 22.0074f, 12.7838f, 22.0074f, 12.0209f)
                curveTo(22.0074f, 11.2581f, 21.5641f, 10.5933f, 20.8992f, 10.2573f)
                lineTo(20.8992f, 10.2503f)
                close()
            }

            path(
                    fill = SolidColor(Color(0xFF313234)),
                    strokeLineWidth = 1f,
            ) {
                moveTo(5.0739f, 4.4977f)
                curveTo(5.0296f, 4.6656f, 5.0f, 4.8336f, 5.0f, 5.0156f)
                lineTo(5.0f, 18.9915f)
                curveTo(5.0f, 19.1734f, 5.0222f, 19.3414f, 5.0739f, 19.5093f)
                lineTo(13.0f, 12.0f)
                lineTo(5.0739f, 4.4977f)
                close()
            }

            path(
                    fill = SolidColor(Color(0xCC313234)),
                    strokeLineWidth = 1f,
                    strokeAlpha = 0.8f,
            ) {
                moveTo(13.0f, 12.0f)
                lineTo(17.0742f, 8.1445f)
                lineTo(8.2212f, 3.2869f)
                curveTo(7.9035f, 3.105f, 7.5267f, 3.0f, 7.1204f, 3.0f)
                curveTo(6.1452f, 3.0f, 5.3106f, 3.6501f, 5.0742f, 4.5039f)
                lineTo(13.0f, 12.0f)
                close()
            }
        }.build().also {
            _googlePlay = it
        }
    }

private var _googlePlay: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun GooglePlayIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcon.GooglePlay,
            contentDescription = null,
    )
}
