@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.compose.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.*
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.compose.BezierIcon

val BezierIcon.LinkCopy: ImageVector
    get() {
        return _linkCopy ?: ImageVector.Builder(
                name = "LinkCopy",
                defaultWidth = 24.dp,
                defaultHeight = 24.dp,
                viewportWidth = 24f,
                viewportHeight = 24f,
        ).apply {
            path(
                    fill = SolidColor(Color(0xFF313234)),
                    strokeLineWidth = 1f,
                    pathFillType = PathFillType.EvenOdd,
            ) {
                moveTo(19.3581f, 4.6301f)
                curveTo(18.5179f, 3.79f, 17.1554f, 3.79f, 16.3153f, 4.6301f)
                curveTo(15.9247f, 5.0206f, 15.2916f, 5.0206f, 14.901f, 4.6301f)
                curveTo(14.5105f, 4.2396f, 14.5105f, 3.6064f, 14.901f, 3.2159f)
                curveTo(16.5222f, 1.5947f, 19.1511f, 1.5947f, 20.7723f, 3.2159f)
                curveTo(22.3934f, 4.837f, 22.3935f, 7.4658f, 20.7724f, 9.087f)
                lineTo(18.1963f, 11.664f)
                curveTo(16.5744f, 13.2848f, 13.9461f, 13.2855f, 12.3241f, 11.6645f)
                curveTo(11.9334f, 11.2741f, 11.9332f, 10.641f, 12.3236f, 10.2503f)
                curveTo(12.714f, 9.8597f, 13.3472f, 9.8595f, 13.7379f, 10.2499f)
                curveTo(14.5787f, 11.0902f, 15.9411f, 11.0902f, 16.7822f, 10.2496f)
                lineTo(19.358f, 7.673f)
                curveTo(20.1981f, 6.8329f, 20.1982f, 5.4703f, 19.3581f, 4.6301f)
                close()
                moveTo(15.2426f, 8.7459f)
                curveTo(14.4027f, 7.906f, 13.0396f, 7.9061f, 12.1991f, 8.7465f)
                lineTo(9.6301f, 11.3156f)
                curveTo(8.79f, 12.1557f, 8.79f, 13.5182f, 9.6301f, 14.3584f)
                curveTo(10.4702f, 15.1985f, 11.832f, 15.1985f, 12.6721f, 14.3584f)
                curveTo(13.0627f, 13.9679f, 13.6958f, 13.9679f, 14.0863f, 14.3584f)
                curveTo(14.4769f, 14.7489f, 14.4769f, 15.3821f, 14.0863f, 15.7726f)
                curveTo(12.4652f, 17.3938f, 9.8371f, 17.3938f, 8.2159f, 15.7726f)
                curveTo(6.5947f, 14.1514f, 6.5947f, 11.5225f, 8.2159f, 9.9014f)
                lineTo(10.7849f, 7.3323f)
                curveTo(12.4059f, 5.7114f, 15.0354f, 5.7102f, 16.6568f, 7.3317f)
                curveTo(17.0473f, 7.7222f, 17.0473f, 8.3554f, 16.6568f, 8.7459f)
                curveTo(16.2663f, 9.1364f, 15.6331f, 9.1364f, 15.2426f, 8.7459f)
                close()
                moveTo(7.8542f, 5.0512f)
                curveTo(8.396f, 5.0069f, 9.0731f, 5.0009f, 10.0f, 5.0001f)
                lineTo(10.0f, 3.0001f)
                curveTo(9.0792f, 3.0007f, 8.3198f, 3.0065f, 7.6914f, 3.0578f)
                curveTo(6.9625f, 3.1174f, 6.3223f, 3.2432f, 5.7301f, 3.545f)
                curveTo(4.7892f, 4.0243f, 4.0243f, 4.7892f, 3.545f, 5.7301f)
                curveTo(3.2432f, 6.3223f, 3.1174f, 6.9625f, 3.0578f, 7.6914f)
                curveTo(3.0f, 8.3993f, 3.0f, 9.2734f, 3.0f, 10.3572f)
                lineTo(3.0f, 13.6428f)
                curveTo(3.0f, 14.7266f, 3.0f, 15.6007f, 3.0578f, 16.3086f)
                curveTo(3.1174f, 17.0375f, 3.2432f, 17.6777f, 3.545f, 18.27f)
                curveTo(4.0243f, 19.2108f, 4.7892f, 19.9757f, 5.7301f, 20.455f)
                curveTo(6.3223f, 20.7568f, 6.9625f, 20.8826f, 7.6914f, 20.9422f)
                curveTo(8.3992f, 21.0f, 9.2733f, 21.0f, 10.3571f, 21.0f)
                lineTo(10.3572f, 21.0f)
                lineTo(13.6428f, 21.0f)
                lineTo(13.6429f, 21.0f)
                curveTo(14.7267f, 21.0f, 15.6008f, 21.0f, 16.3086f, 20.9422f)
                curveTo(17.0375f, 20.8826f, 17.6777f, 20.7568f, 18.27f, 20.455f)
                curveTo(19.2108f, 19.9757f, 19.9757f, 19.2108f, 20.455f, 18.27f)
                curveTo(20.7568f, 17.6777f, 20.8826f, 17.0375f, 20.9422f, 16.3086f)
                curveTo(20.9935f, 15.6802f, 20.9993f, 14.9208f, 20.9999f, 14.0f)
                lineTo(18.9999f, 14.0f)
                curveTo(18.9991f, 14.9269f, 18.9931f, 15.604f, 18.9488f, 16.1458f)
                curveTo(18.8994f, 16.7509f, 18.8072f, 17.0986f, 18.673f, 17.362f)
                curveTo(18.3854f, 17.9265f, 17.9265f, 18.3854f, 17.362f, 18.673f)
                curveTo(17.0986f, 18.8072f, 16.7509f, 18.8994f, 16.1458f, 18.9488f)
                curveTo(15.5289f, 18.9992f, 14.7366f, 19.0f, 13.6f, 19.0f)
                lineTo(10.4f, 19.0f)
                curveTo(9.2634f, 19.0f, 8.4711f, 18.9992f, 7.8542f, 18.9488f)
                curveTo(7.2491f, 18.8994f, 6.9014f, 18.8072f, 6.638f, 18.673f)
                curveTo(6.0735f, 18.3854f, 5.6146f, 17.9265f, 5.327f, 17.362f)
                curveTo(5.1928f, 17.0986f, 5.1006f, 16.7509f, 5.0512f, 16.1458f)
                curveTo(5.0008f, 15.5289f, 5.0f, 14.7366f, 5.0f, 13.6f)
                lineTo(5.0f, 10.4f)
                curveTo(5.0f, 9.2634f, 5.0008f, 8.4711f, 5.0512f, 7.8542f)
                curveTo(5.1006f, 7.2491f, 5.1928f, 6.9014f, 5.327f, 6.638f)
                curveTo(5.6146f, 6.0735f, 6.0735f, 5.6146f, 6.638f, 5.327f)
                curveTo(6.9014f, 5.1928f, 7.2491f, 5.1006f, 7.8542f, 5.0512f)
                close()
            }
        }.build().also {
            _linkCopy = it
        }
    }

private var _linkCopy: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun LinkCopyIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcon.LinkCopy,
            contentDescription = null,
    )
}
