@file:Suppress("ObjectPropertyName", "UnusedReceiverParameter")

// Auto-generated by script/generate_compose_bezier_icon.py

package io.channel.bezier.compose.icon

import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.*
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import io.channel.bezier.compose.BezierIcon

val BezierIcon.VolumeOffFilled: ImageVector
    get() {
        return _volumeOffFilled ?: ImageVector.Builder(
                name = "VolumeOffFilled",
                defaultWidth = 24.dp,
                defaultHeight = 24.dp,
                viewportWidth = 24f,
                viewportHeight = 24f,
        ).apply {
            path(
                    fill = SolidColor(Color(0xFF313234)),
                    strokeLineWidth = 1f,
                    pathFillType = PathFillType.EvenOdd,
            ) {
                moveTo(21.5461f, 19.425f)
                curveTo(21.9366f, 19.8155f, 21.9366f, 20.4485f, 21.5461f, 20.839f)
                curveTo(21.1556f, 21.2295f, 20.5226f, 21.2295f, 20.1321f, 20.839f)
                lineTo(3.1611f, 3.868f)
                curveTo(2.7706f, 3.4775f, 2.7706f, 2.8445f, 3.1611f, 2.454f)
                curveTo(3.5516f, 2.0635f, 4.1846f, 2.0635f, 4.5751f, 2.454f)
                lineTo(8.3541f, 6.233f)
                lineTo(12.2931f, 2.293f)
                curveTo(12.4811f, 2.106f, 12.7351f, 2.0f, 13.0001f, 2.0f)
                lineTo(14.0001f, 2.0f)
                curveTo(14.5521f, 2.0f, 15.0001f, 2.448f, 15.0001f, 3.0f)
                lineTo(15.0001f, 12.879f)
                lineTo(21.5461f, 19.425f)
                close()
                moveTo(2.0002f, 8.0001f)
                curveTo(2.0002f, 7.4481f, 2.4482f, 7.0001f, 3.0002f, 7.0001f)
                lineTo(4.8792f, 7.0001f)
                lineTo(15.0002f, 17.1211f)
                lineTo(15.0002f, 21.0001f)
                curveTo(15.0002f, 21.5521f, 14.5522f, 22.0001f, 14.0002f, 22.0001f)
                lineTo(13.0002f, 22.0001f)
                curveTo(12.7352f, 22.0001f, 12.4802f, 21.8951f, 12.2932f, 21.7071f)
                lineTo(7.5862f, 17.0001f)
                lineTo(3.0002f, 17.0001f)
                curveTo(2.4482f, 17.0001f, 2.0002f, 16.5521f, 2.0002f, 16.0001f)
                lineTo(2.0002f, 8.0001f)
                close()
            }
        }.build().also {
            _volumeOffFilled = it
        }
    }

private var _volumeOffFilled: ImageVector? = null

@Preview(showBackground = true)
@Composable
private fun VolumeOffFilledIconPreview() {
    Icon(
            modifier = Modifier.size(128.dp),
            imageVector = BezierIcon.VolumeOffFilled,
            contentDescription = null,
    )
}
